import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {visualValue,elementCSS} from '../shared/element-system.mjs';import {localStylePath,BLUE_THEME} from '../shared/building-blocks.mjs';import {GAME_MODES,resolveRoute,validateNavigation,routeKey} from '../shared/navigation.mjs';import {validateConfig} from '../design-system/model.mjs';import {designFields} from '../design-system/project-model.mjs';
const base=JSON.parse(await readFile(new URL('../design-system/config.json',import.meta.url)));
test('PIN and no PIN override only the currently visible state, preserving recipe and view cascade',()=>{const config={elementStyles:{'container-pin-card':{radius:24,height:0}},elementOverrides:{'player-pin':{'pin-card':{padding:16}}},elementStates:{'player-pin':{pin:{'pin-card':{height:410}},'no-pin':{'pin-card':{height:220}}}}};const item={id:'pin-card',recipe:'container-pin-card',kind:'container'};assert.deepEqual(visualValue(config,'player-pin',{...item,state:'pin'}),{radius:24,height:410,padding:16});assert.equal(visualValue(config,'player-pin',{...item,state:'no-pin'}).height,220);assert.equal(localStylePath('player-pin',{...item,state:'no-pin'}),'elementStates.player-pin.no-pin.pin-card');assert.match(elementCSS(config),/ds-component-state="no-pin"/);});
test('global recipe updates propagate; family edits stay within their family',()=>{const config={elementStyles:{'jelly-option':{activeAnimation:'pulse',idleAnimation:'none'}},familyStyles:{math:{'jelly-option':{animationDistance:9}}}};for(const mode of GAME_MODES){const s=visualValue(config,mode+'-settings',{recipe:'jelly-option',mode,state:'default'});assert.equal(s.activeAnimation,'pulse');assert.equal(s.idleAnimation,'none');assert.equal(s.animationDistance,mode==='math'?9:undefined);}});
test('every mode exits to its own setup, round results share contextual routes',()=>{for(const mode of GAME_MODES){assert.equal(resolveRoute({},mode+'-initial','exit-confirm',mode),mode+'-settings');assert.equal(resolveRoute({},mode+'-results','result-back',mode),mode+'-settings');assert.equal(resolveRoute({},mode+'-results','history',mode),'progress');assert.equal(resolveRoute({},'progress','return-results',mode,mode+'-results'),mode+'-results');assert.equal(resolveRoute({},mode+'-settings','home',mode),'home');}});
test('contextual route editing and all new fields survive saved design snapshots',()=>{const config=structuredClone(base);config.navigation={routes:{[routeKey('progress','return-results','math-results')]:'math-settings'}};config.familyTokens={math:{jelly:{duration:700}}};config.familyStyles={math:{'jelly-option':{activeAnimation:'pulse'}}};config.elementStates={'player-pin':{'no-pin':{'pin-card':{height:220}}}};validateConfig(config);assert.equal(resolveRoute(config,'progress','return-results','math','math-results'),'math-settings');const saved=designFields(config);for(const key of ['navigation','familyTokens','familyStyles','elementStates'])assert.deepEqual(saved[key],config[key]);assert.throws(()=>validateNavigation({routes:{'home--home':'unknown'}}));});

test('editable default blue palette and state visibility survive the test build contract',async()=>{const {optimizedTestConfig,assertVisibilityReadyForProduction}=await import('../design-system/pwa-test-build.mjs');const c=structuredClone(base);c.defaultTheme={...BLUE_THEME,accent:'#2255aa'};c.elementStates={'player-pin':{'no-pin':{'pin-card':{visibility:'hidden'}}}};validateConfig(c);const built=optimizedTestConfig(c);assert.equal(built.config.defaultTheme.accent,'#2255aa');assert.ok(built.report.hidden.some(r=>r.scope==='state'&&r.state==='no-pin'));assert.deepEqual(designFields(c).defaultTheme,c.defaultTheme);c.project={designDraft:{elementStates:{'player-pin':{'no-pin':{'pin-card':{visibility:'removed'}}}}}};assert.throws(()=>assertVisibilityReadyForProduction(c));});
