import test from 'node:test';
import assert from 'node:assert/strict';
import {componentTree,screenLabel} from '../design-system/component-tree.mjs';
import {validateElementStyles,visualValue} from '../shared/element-system.mjs';
const rows=[{id:'layout-root',label:'Ekran'},{id:'card',parent:'layout-root',order:1,visible:true},{id:'group3',parent:'card',visible:true},{id:'slider',parent:'group3',revealable:true},{id:'3min',parent:'slider',revealable:true},{id:'background',parent:'layout-root',kind:'background',order:20,visible:true}];
test('full ancestry is retained for a conditional leaf; the backdrop comes first',()=>{const tree=componentTree(rows);assert.deepEqual(tree.path('3min').map(n=>n.id),['layout-root','card','group3','slider','3min']);assert.deepEqual(tree.children.get('layout-root').map(n=>n.id),['background','card']);assert.equal(tree.available(rows[4]),true);assert.equal(tree.available({visible:false}),false);assert.equal(tree.available({visible:false,temporary:'hidden'}),true);});
test('broken ancestry terminates and disconnected nodes return to the screen',()=>{const tree=componentTree([{id:'layout-root'},{id:'a',parent:'b'},{id:'b',parent:'a'},{id:'c',parent:'missing'}]);assert.equal(tree.path('a').length,2);assert.equal(tree.children.get('layout-root')[0].id,'c');});
test('screen names omit the already selected game mode',()=>{assert.equal(screenLabel({name:'Ortografia · ustawienia'}),'Ustawienia');assert.equal(screenLabel({name:'Nowy gracz'}),'Nowy gracz');});
test('local text is validated and does not leak between instances or views',()=>{const config={elementOverrides:{'spelling-settings':{heading:{text:'Moja misja'}}}};validateElementStyles(config);assert.equal(visualValue(config,'spelling-settings',{id:'heading',kind:'text'}).text,'Moja misja');assert.equal(visualValue(config,'english-settings',{id:'heading',kind:'text'}).text,undefined);assert.equal(visualValue(config,'spelling-settings',{id:'other',kind:'text'}).text,undefined);for(const text of ['',23,'a'.repeat(601)])assert.throws(()=>validateElementStyles({elementOverrides:{home:{heading:{text}}}}));});
