import test from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULT_WORD_TRANSITION,localPieceRoute,MAX_WORD_PIECES} from '../spelling/word-particles.mjs';
import {normalizeEffectsConfig,validateEffects,DEFAULT_EFFECTS} from '../spelling/effect-model.mjs';
test('organic local routes stay bounded by the selected spread',()=>{const a={x:10,y:20},b={x:50,y:80},c={...DEFAULT_WORD_TRANSITION,spread:40,randomness:.8};for(const r of [0,.3,.7,1]){const p=localPieceRoute(a,b,c,()=>r);assert.ok(Math.hypot(p.x-30,p.y-50)<=32.0001);}assert.equal(DEFAULT_WORD_TRANSITION.piecesPerLetter,144);assert.equal(MAX_WORD_PIECES,1200);});
test('word tile settings validate tuning and bounded piece density',()=>{validateEffects(normalizeEffectsConfig({...DEFAULT_EFFECTS,wordTransition:{piecesPerLetter:180,duration:1800,chromatic:4,jitter:3,spread:0,drift:1200}}));for(const patch of [{piecesPerLetter:181},{chromatic:5},{jitter:4},{drift:1201}])assert.throws(()=>validateEffects(normalizeEffectsConfig({...DEFAULT_EFFECTS,wordTransition:patch})));});

test('photo deformation never forces a polygon cycle or mutates saved configuration',()=>{const value={...DEFAULT_EFFECTS,bubble:{...DEFAULT_EFFECTS.bubble,transforms:true,shape:'bubble'}};assert.equal(normalizeEffectsConfig(value).bubble.shape,'bubble');assert.equal(value.bubble.shape,'bubble');assert.equal(normalizeEffectsConfig(DEFAULT_EFFECTS).bubble.shape,'bubble');});

test('production selection and font completion settings survive the shared contract',()=>{for(const renderer of ['classic','composited'])assert.equal(normalizeEffectsConfig({...DEFAULT_EFFECTS,bubble:{renderer}}).bubble.renderer,renderer);const word={letterSpacing:12,particleSpacing:6,strokeMagnet:1,settleFill:1,colorSpread:1,colorDeviation:1,colorSpeed:3};validateEffects(normalizeEffectsConfig({...DEFAULT_EFFECTS,wordTransition:word}));for(const patch of [{letterSpacing:13},{particleSpacing:-1},{strokeMagnet:2},{settleFill:1.1},{colorDeviation:2},{colorSpeed:4}])assert.throws(()=>validateEffects(normalizeEffectsConfig({...DEFAULT_EFFECTS,wordTransition:patch})));});

test('contour options and production reactions round-trip with bounded settings',()=>{const c=normalizeEffectsConfig({wordTransition:{clipToFont:false,contourDeparture:3,bubbleGap:24},bubble:{correctGrowth:.2,correctGrowthDuration:2400,comboWave:3,comboDuration:4000,transitionZoom:-6,transitionRotate:-12,transitionHue:-180}});validateEffects(c);assert.equal(c.wordTransition.clipToFont,false);assert.equal(c.bubble.transitionHue,-180);for(const patch of [{clipToFont:'false'},{contourDeparture:4},{bubbleGap:-1}])assert.throws(()=>validateEffects(normalizeEffectsConfig({wordTransition:patch})));for(const patch of [{correctGrowth:.3},{comboWave:4},{transitionZoom:20}])assert.throws(()=>validateEffects(normalizeEffectsConfig({bubble:patch})));});
