import test from 'node:test';
import assert from 'node:assert/strict';
import {sampleInkPoints,advancePiece,separatePieces,DEFAULT_WORD_TRANSITION,strokeDistanceField,strokeRidge,particlePalette,spaceInkPoints} from '../spelling/word-particles.mjs';
function random(seed=42){return ()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32;};}
test('ink sampling preserves silhouette and holes, without slicing a rectangle into rows',()=>{const pixels=[];for(let y=0;y<30;y++)for(let x=0;x<30;x++)if(x<8||y<8)pixels.push([x,y]);const points=sampleInkPoints(pixels,144,random());assert.equal(points.length,144);assert.ok(points.every(([x,y])=>x<8.3||y<8.3));assert.equal(new Set(points.map(([x,y])=>x+':'+y)).size,144);assert.ok(points.some(([x])=>x%1!==0));});
test('long particle simulation stays local, finite and readable after drift',()=>{const p={x:0,y:0,tx:25,ty:40,vx:4,vy:-3,seed:1.3,frequency:.91,alpha:0,born:0,side:'left'};for(let t=0;t<120000;t+=33.33)advancePiece(p,DEFAULT_WORD_TRANSITION,t,33.33,{x:50,y:-150});assert.ok(Number.isFinite(p.x)&&Number.isFinite(p.y));assert.ok(Math.hypot(p.x-p.tx,p.y-p.ty)<4);assert.equal(p.alpha,1);});
test('opposite sides and answer directions give independent currents',()=>{const initial={x:0,y:0,tx:0,ty:0,vx:0,vy:0,seed:1,frequency:1,alpha:1,born:0};const left={...initial,side:'left'},right={...initial,side:'right'};for(let t=0;t<300;t+=33)for(const p of [left,right])advancePiece(p,DEFAULT_WORD_TRANSITION,t,33,{x:0,y:-100});assert.notEqual(left.x,right.x);});
test('local collisions share impulse between neighbours',()=>{const a={x:0,y:0,vx:0,vy:0},b={x:1,y:0,vx:0,vy:0};separatePieces([a,b],2);assert.ok(a.vx<0&&b.vx>0);assert.equal(a.vx+b.vx,0);});

test('stroke magnet moves toward local stroke centre and keeps the counter empty',()=>{const width=13,height=13,mask=Uint8Array.from({length:width*height},(_,i)=>{const x=i%width,y=Math.floor(i/width);return x>0&&x<12&&y>0&&y<12&&!(x>=5&&x<=7&&y>=5&&y<=7)?1:0;});const field=strokeDistanceField(mask,width,height);for(const [x,y]of [[1,4],[4,1],[11,8],[8,11]]){const [rx,ry]=strokeRidge(x,y,field);assert.ok(field.distance[ry*width+rx]>=field.distance[y*width+x]);assert.equal(mask[ry*width+rx],1);}assert.equal(field.distance[6*width+6],0);});
test('colour deviation zero retains source ink; animated spread remains bounded',()=>{const c={...DEFAULT_WORD_TRANSITION,colorVariation:0,colorDeviation:0};assert.ok(particlePalette('rgb(12, 8, 57)',c,9000).every(x=>x==='rgb(12,8,57)'));const colourful={...c,colorDeviation:1,colorSpread:1,colorSpeed:2};const a=particlePalette('rgb(12, 8, 57)',colourful,0),b=particlePalette('rgb(12, 8, 57)',colourful,2000);assert.notDeepEqual(a,b);assert.ok(new Set(a).size>8);for(const color of b)for(const value of color.match(/\d+/g))assert.ok(Number(value)<=210&&Number(value)>=0);});

test('inter-particle distance allows overlap at zero and limits neighbouring centres',()=>{const points=Array.from({length:30},(_,i)=>[i%6,Math.floor(i/6)]);assert.equal(spaceInkPoints(points,0).length,30);const spaced=spaceInkPoints(points,2.5);assert.ok(spaced.length<30);for(let i=0;i<spaced.length;i++)for(let j=i+1;j<spaced.length;j++)assert.ok(Math.hypot(spaced[i][0]-spaced[j][0],spaced[i][1]-spaced[j][1])>=2.5);});
