export const SCENES = new Map([
  ['r_ża', { key:'rose', asset:'rose.webp', layouts:['bubble'] }],
  ['kr_lik', { key:'bunny', asset:'bunny.webp', layouts:['bubble'] }],
  ['g_ry', { key:'mountains', asset:'mountains.webp', layouts:['bubble'] }],
  ['g_ra', { key:'mountains', asset:'mountains.webp', layouts:['bubble'] }],
  ['ż_łw', { key:'turtle', asset:'turtle.avif', layouts:['bubble'] }],
  ['wr_bel', { key:'sparrow', asset:'sparrow.avif', layouts:['bubble'] }],
  ['jask_łka', { key:'swallow', asset:'swallow.avif', layouts:['bubble'] }],
  ['_mury', { key:'clouds', asset:'clouds-review.webp', layouts:['bubble'] }],
  ['kr_l', { key:'king', asset:'krol.avif', layouts:['bubble'] }],
  ['c_rka', { key:'corka', asset:'corka.avif', layouts:['bubble'] }],
  ['w_zek', { key:'wozek', asset:'wozek.avif', layouts:['bubble'] }],
  ['pi_ro', { key:'pioro', asset:'pioro.avif', layouts:['bubble'] }],
  ['_semka', { key:'osemka', asset:'osemka.avif', layouts:['bubble'] }],
  ['sk_ra', { key:'skora', asset:'skora.webp', layouts:['bubble'] }],
  ['ż_łty', { key:'zolty', asset:'zolty.webp', layouts:['bubble'] }],
  ['st_ł', { key:'stol', asset:'stol.webp', layouts:['bubble'] }],
  ['samoch_d', { key:'samochod', asset:'samochod.webp', layouts:['bubble'] }],
  ['_aba', { key:'zaba', asset:'zaba.avif', layouts:['bubble'] }],
  ['leka_', { key:'lekarz', asset:'lekarz.avif', layouts:['bubble'] }],
  ['g_yb', { key:'grzyb', asset:'grzyb.webp', layouts:['bubble'] }],
  ['s_ody', { key:'schody', asset:'schody.webp', layouts:['bubble'] }],
  ['je_', { key:'jez', asset:'jez.webp', layouts:['bubble'] }],
  ['ksią_ka', { key:'ksiazka', asset:'ksiazka.webp', layouts:['bubble'] }],
  ['g_ral', { key:'mountains', asset:'mountains.webp', layouts:['bubble'] }],
  ['g_rski', { key:'mountains', asset:'mountains.webp', layouts:['bubble'] }],
  ['t_rysta', { key:'mountains', asset:'mountains.webp', layouts:['bubble'] }],
  ['ogr_d', { key:'garden', asset:'rose.webp', layouts:['bubble'] }],
  ['r_żowy', { key:'pink', asset:'corka.avif', layouts:['bubble'] }],
  ['b_ty', { key:'yellow-boots', asset:'zolty.webp', layouts:['bubble'] }],
  ['_lewa', { key:'rain', asset:'zolty.webp', layouts:['bubble'] }],
  ['kapt_rek', { key:'yellow-hood', asset:'zolty.webp', layouts:['bubble'] }],
  ['k_bek', { key:'table-cup', asset:'stol.webp', layouts:['bubble'] }],
  ['_lica', { key:'street', asset:'samochod.webp', layouts:['bubble'] }],
  ['_branie', { key:'clothes', asset:'zolty.webp', layouts:['bubble'] }],
  ['k_rtka', { key:'yellow-coat', asset:'zolty.webp', layouts:['bubble'] }],
  ['p_chaty', { key:'bunny', asset:'bunny.webp', layouts:['bubble'] }],
  ['p_łka', { key:'bookshelf', asset:'ksiazka.webp', layouts:['bubble'] }],
  ['p_łnoc', { key:'clouds', asset:'clouds-review.webp', layouts:['bubble'] }],
  ['_śmiech', { key:'bunny', asset:'bunny.webp', layouts:['bubble'] }],
  ['_rlop', { key:'mountains', asset:'mountains.webp', layouts:['bubble'] }],
  ['_rodziny', { key:'birthday', asset:'osemka.avif', layouts:['bubble'] }],
  ['_uragan', { key:'huragan', asset:'huragan.webp', layouts:['bubble'] }],
  ['g_ebień', { key:'comb', asset:'comb.avif', layouts:['bubble'] }],
  ['sok_ł', { key:'sokol', asset:'sokol.webp', layouts:['bubble'] }],
]);

export const WORD_SCENES = new Map([
  // Distinct prepared illustrations added in v23.
  ['drzewo', { key:'drzewo', asset:'drzewo.webp', layouts:['bubble'] }],
  ['zima', { key:'zima', asset:'zima.webp', layouts:['bubble'] }],
  ['śnieg', { key:'zima', asset:'zima.webp', layouts:['bubble'] }],
  ['ogórek', { key:'ogorek', asset:'ogorek.webp', layouts:['bubble'] }],
  ['wiewiórka', { key:'wiewiorka', asset:'wiewiorka.webp', layouts:['bubble'] }],

  ['źródło', { key:'mountain-source', asset:'mountains.webp', layouts:['bubble'] }],
  ['półwysep', { key:'mountain-peninsula', asset:'mountains.webp', layouts:['bubble'] }],
  ['horyzont', { key:'mountain-horizon', asset:'mountains.webp', layouts:['bubble'] }],
  ['niebo', { key:'sky', asset:'swallow.avif', layouts:['bubble'] }],
  ['chmura', { key:'cloud', asset:'clouds-review.webp', layouts:['bubble'] }],
  ['burza', { key:'storm-cloud', asset:'clouds-review.webp', layouts:['bubble'] }],
  ['dach', { key:'castle-roof', asset:'castle-review.webp', layouts:['bubble'] }],
  ['chata', { key:'castle-cottage', asset:'castle-review.webp', layouts:['bubble'] }],
  ['wieża', { key:'castle-tower', asset:'castle-review.webp', layouts:['bubble'] }],
  ['tulipan', { key:'garden-tulip', asset:'rose.webp', layouts:['bubble'] }],
  ['rzodkiewka', { key:'garden-radish', asset:'rose.webp', layouts:['bubble'] }],
  ['korzeń', { key:'drzewo', asset:'drzewo.webp', layouts:['bubble'] }],
  ['brzoza', { key:'garden-birch', asset:'rose.webp', layouts:['bubble'] }],
  ['krzak', { key:'garden-bush', asset:'rose.webp', layouts:['bubble'] }],
  ['wrzos', { key:'garden-heather', asset:'rose.webp', layouts:['bubble'] }],
  ['przyroda', { key:'nature', asset:'mountains.webp', layouts:['bubble'] }],
  ['przygoda', { key:'adventure', asset:'mountains.webp', layouts:['bubble'] }],
  ['historia', { key:'story', asset:'ksiazka.webp', layouts:['bubble'] }],
  ['państwo', { key:'kingdom', asset:'krol.avif', layouts:['bubble'] }],
  ['herb', { key:'royal-crest', asset:'krol.avif', layouts:['bubble'] }],
  ['honor', { key:'royal-honor', asset:'krol.avif', layouts:['bubble'] }],
  ['bohater', { key:'hero', asset:'krol.avif', layouts:['bubble'] }],
  ['chleb', { key:'cottage-table', asset:'stol.webp', layouts:['bubble'] }],
  ['herbata', { key:'cottage-table', asset:'stol.webp', layouts:['bubble'] }],
  ['kuchnia', { key:'cottage-table', asset:'stol.webp', layouts:['bubble'] }],
  ['kuchenka', { key:'cottage-table', asset:'stol.webp', layouts:['bubble'] }],
  ['kucharz', { key:'cottage-table', asset:'stol.webp', layouts:['bubble'] }],
  ['ciasto', { key:'cottage-table', asset:'stol.webp', layouts:['bubble'] }],
  ['rzemiosło', { key:'leather-craft', asset:'skora.webp', layouts:['bubble'] }],
  ['fartuch', { key:'leather-craft', asset:'skora.webp', layouts:['bubble'] }],
  ['choroba', { key:'medical', asset:'lekarz.avif', layouts:['bubble'] }],
  ['chory', { key:'medical', asset:'lekarz.avif', layouts:['bubble'] }],
  ['chirurg', { key:'medical', asset:'lekarz.avif', layouts:['bubble'] }],
  ['pomóc', { key:'medical-help', asset:'lekarz.avif', layouts:['bubble'] }],
  ['mózg', { key:'medical-brain', asset:'lekarz.avif', layouts:['bubble'] }],
  ['dziecko', { key:'child', asset:'wozek.avif', layouts:['bubble'] }],
  ['maluch', { key:'child', asset:'wozek.avif', layouts:['bubble'] }],
  ['śmiech', { key:'happy-bunny', asset:'bunny.webp', layouts:['bubble'] }],
  ['siedem', { key:'number-play', asset:'osemka.avif', layouts:['bubble'] }],
  ['usterka', { key:'car-service', asset:'samochod.webp', layouts:['bubble'] }],

  ['wulkan', { key:'mountain-volcano', asset:'mountains.webp', layouts:['bubble'] }],
  ['rzeka', { key:'mountain-river', asset:'mountains.webp', layouts:['bubble'] }],
  ['brzeg', { key:'mountain-shore', asset:'mountains.webp', layouts:['bubble'] }],
  ['wyżej', { key:'mountain-up', asset:'mountains.webp', layouts:['bubble'] }],
  ['niżej', { key:'mountain-down', asset:'mountains.webp', layouts:['bubble'] }],
  ['bliżej', { key:'mountain-near', asset:'mountains.webp', layouts:['bubble'] }],
  ['świeży', { key:'garden-fresh', asset:'rose.webp', layouts:['bubble'] }],
  ['warzywo', { key:'garden-vegetable', asset:'rose.webp', layouts:['bubble'] }],
  ['rzepa', { key:'garden-turnip', asset:'rose.webp', layouts:['bubble'] }],
  ['zioło', { key:'garden-herb', asset:'rose.webp', layouts:['bubble'] }],
  ['ziemia', { key:'garden-earth', asset:'rose.webp', layouts:['bubble'] }],
  ['zielony', { key:'drzewo', asset:'drzewo.webp', layouts:['bubble'] }],
  ['trzcina', { key:'garden-reed', asset:'rose.webp', layouts:['bubble'] }],
  ['chmiel', { key:'garden-hops', asset:'rose.webp', layouts:['bubble'] }],
  ['chrzan', { key:'garden-horseradish', asset:'rose.webp', layouts:['bubble'] }],
  ['cukier', { key:'table-food', asset:'stol.webp', layouts:['bubble'] }],
  ['zupa', { key:'table-food', asset:'stol.webp', layouts:['bubble'] }],
  ['burak', { key:'table-food', asset:'stol.webp', layouts:['bubble'] }],
  ['ugotować', { key:'table-cooking', asset:'stol.webp', layouts:['bubble'] }],
  ['hamburger', { key:'table-food', asset:'stol.webp', layouts:['bubble'] }],
  ['suchar', { key:'table-food', asset:'stol.webp', layouts:['bubble'] }],
  ['okruch', { key:'table-food', asset:'stol.webp', layouts:['bubble'] }],
  ['łyżeczka', { key:'table-spoon', asset:'stol.webp', layouts:['bubble'] }],
  ['pożywienie', { key:'table-food', asset:'stol.webp', layouts:['bubble'] }],
  ['ucho', { key:'medical-ear', asset:'lekarz.avif', layouts:['bubble'] }],
  ['uszy', { key:'medical-ear', asset:'lekarz.avif', layouts:['bubble'] }],
  ['źrenica', { key:'medical-eye', asset:'lekarz.avif', layouts:['bubble'] }],
  ['oddech', { key:'medical-breath', asset:'lekarz.avif', layouts:['bubble'] }],
  ['higiena', { key:'medical-hygiene', asset:'lekarz.avif', layouts:['bubble'] }],
  ['uczeń', { key:'study', asset:'ksiazka.webp', layouts:['bubble'] }],
  ['uczennica', { key:'study', asset:'ksiazka.webp', layouts:['bubble'] }],
  ['ćwiczyć', { key:'study-exercise', asset:'ksiazka.webp', layouts:['bubble'] }],
  ['ćwiczenie', { key:'study-exercise', asset:'ksiazka.webp', layouts:['bubble'] }],
  ['hasło', { key:'study-password', asset:'ksiazka.webp', layouts:['bubble'] }],
  ['przykład', { key:'study-example', asset:'ksiazka.webp', layouts:['bubble'] }],
  ['numer', { key:'number-play', asset:'osemka.avif', layouts:['bubble'] }],
  ['punkt', { key:'number-play', asset:'osemka.avif', layouts:['bubble'] }],
  ['ćwierć', { key:'number-play', asset:'osemka.avif', layouts:['bubble'] }],
  ['wnuk', { key:'family-child', asset:'wozek.avif', layouts:['bubble'] }],
  ['wnuczka', { key:'family-child', asset:'wozek.avif', layouts:['bubble'] }],
]);

export function sceneFor(masked, word=''){ return WORD_SCENES.get(word) || SCENES.get(masked) || null; }
export function chooseLayout(){ return 'bubble'; }
export function sceneUrl(scene){
  if(!scene) return '';
  const url = new URL(`../assets/scenes/${scene.asset || `${scene.key}.svg`}`, import.meta.url);
  url.searchParams.set('v', '23-art-library');
  return url.href;
}
