export const SCENES = new Map([
  ['r_ża', { key:'rose', asset:'rose.webp', layouts:['bubble'] }],
  ['kr_lik', { key:'bunny', asset:'bunny.webp', layouts:['bubble'] }],
  ['g_ry', { key:'mountains', asset:'mountains.webp', layouts:['bubble'] }],
  ['g_ra', { key:'mountains', asset:'mountains.webp', layouts:['bubble'] }],
  ['ż_łw', { key:'turtle', asset:'turtle.avif', layouts:['bubble'] }],
  ['wr_bel', { key:'sparrow', asset:'sparrow.avif', layouts:['bubble'] }],
  ['jask_łka', { key:'swallow', asset:'swallow.avif', layouts:['bubble'] }],
  ['_mury', { key:'clouds', asset:'clouds-review.webp', layouts:['bubble'] }],
  ['kr_l', { key:'king', asset:'krol.avif', layouts:['bubble'] }],
  ['c_rka', { key:'corka', asset:'corka.avif', layouts:['bubble'] }],
  ['w_zek', { key:'wozek', asset:'wozek.avif', layouts:['bubble'] }],
  ['pi_ro', { key:'pioro', asset:'pioro.avif', layouts:['bubble'] }],
  ['_semka', { key:'osemka', asset:'osemka.avif', layouts:['bubble'] }],
  ['sk_ra', { key:'skora', asset:'skora.avif', layouts:['bubble'] }],
  ['ż_łty', { key:'zolty', asset:'zolty.avif', layouts:['bubble'] }],
  ['st_ł', { key:'stol', asset:'stol.avif', layouts:['bubble'] }],
  ['samoch_d', { key:'samochod', asset:'samochod.avif', layouts:['bubble'] }],
  ['_aba', { key:'zaba', asset:'zaba.avif', layouts:['bubble'] }],
  ['leka_', { key:'lekarz', asset:'lekarz.avif', layouts:['bubble'] }],
  ['g_yb', { key:'grzyb', asset:'grzyb.avif', layouts:['bubble'] }],
  ['s_ody', { key:'schody', asset:'schody.avif', layouts:['bubble'] }],
  ['je_', { key:'jez', asset:'jez.avif', layouts:['bubble'] }],
  ['ksią_ka', { key:'ksiazka', asset:'ksiazka.avif', layouts:['bubble'] }],
  ['g_ral', { key:'mountains', asset:'mountains.webp', layouts:['bubble'] }],
  ['g_rski', { key:'mountains', asset:'mountains.webp', layouts:['bubble'] }],
  ['t_rysta', { key:'mountains', asset:'mountains.webp', layouts:['bubble'] }],
  ['ogr_d', { key:'garden', asset:'rose.webp', layouts:['bubble'] }],
  ['r_żowy', { key:'pink', asset:'corka.avif', layouts:['bubble'] }],
  ['b_ty', { key:'yellow-boots', asset:'zolty.avif', layouts:['bubble'] }],
  ['_lewa', { key:'rain', asset:'zolty.avif', layouts:['bubble'] }],
  ['kapt_rek', { key:'yellow-hood', asset:'zolty.avif', layouts:['bubble'] }],
  ['k_bek', { key:'table-cup', asset:'stol.avif', layouts:['bubble'] }],
  ['_lica', { key:'street', asset:'samochod.avif', layouts:['bubble'] }],
  ['_branie', { key:'leather', asset:'skora.avif', layouts:['bubble'] }],
  ['k_rtka', { key:'yellow-coat', asset:'zolty.avif', layouts:['bubble'] }],
  ['p_chaty', { key:'bunny', asset:'bunny.webp', layouts:['bubble'] }],
  ['p_łka', { key:'bookshelf', asset:'ksiazka.avif', layouts:['bubble'] }],
  ['p_łnoc', { key:'clouds', asset:'clouds-review.webp', layouts:['bubble'] }],
  ['_śmiech', { key:'bunny', asset:'bunny.webp', layouts:['bubble'] }],
  ['_rlop', { key:'mountains', asset:'mountains.webp', layouts:['bubble'] }],
  ['_rodziny', { key:'birthday', asset:'osemka.avif', layouts:['bubble'] }],
  ['_uragan', { key:'storm', layouts:['bubble'] }],
  ['g_ebień', { key:'comb', asset:'comb.avif', layouts:['bubble'] }],
  ['sok_ł', { key:'falcon', layouts:['bubble'] }],
]);

export function sceneFor(masked){ return SCENES.get(masked) || null; }
export function chooseLayout(){ return 'bubble'; }
export function sceneUrl(scene){
  if(!scene) return '';
  return new URL(`../assets/scenes/${scene.asset || `${scene.key}.svg`}`, import.meta.url).href;
}
