// Shared decoration for every screen and component. Geometry stays untouched.
export const SURFACE_EFFECTS={none:'Bez efektu',noise:'Miękkie ziarno',particles:'Cząsteczki liter / iskry',neon:'Neonowa siatka',shimmer:'Płynny blask obrzeża',bokeh:'Bokeh',bubbles:'Bąble'};
export const SURFACE_FIELDS={effectIntensity:[0,1,.05,'Intensywność'],effectDensity:[1,32,1,'Liczba drobinek'],effectSpeed:[.1,2,.05,'Tempo'],effectSize:[2,80,1,'Wielkość (px)'],effectBlur:[0,12,.5,'Miękkość (px)']};
export const DEFAULT_SURFACE={effect:'none',effectIntensity:.3,effectDensity:12,effectSpeed:.5,effectSize:24,effectBlur:3,effectColor:'#ffd4a3',effectTrigger:'continuous'};
export function surfaceConfig(value={}){return {...DEFAULT_SURFACE,...value};}
export function validateSurface(value){const c=surfaceConfig(value);if(!Object.hasOwn(SURFACE_EFFECTS,c.effect)||!['continuous','tap','answer'].includes(c.effectTrigger)||!/^#[0-9a-f]{6}$/i.test(c.effectColor))throw Error('Nieprawidłowy efekt powierzchni.');for(const [key,[min,max]]of Object.entries(SURFACE_FIELDS))if(!Number.isFinite(c[key])||c[key]<min||c[key]>max)throw Error('Sprawdź parametr efektu: '+key);if(!Number.isInteger(c.effectDensity))throw Error('Liczba drobinek musi być całkowita.');return c;}
const rows=new Map();let screen;
function styles(){if(document.querySelector('link[data-mn-surface-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.dataset.mnSurfaceCss='1';l.href=new URL('./surface-effects.css',import.meta.url).href;document.head.append(l);}
function make(node,value,global=false){
 styles();const c=surfaceConfig(value),layer=document.createElement('div');layer.className='mn-surface-layer mn-surface-'+c.effect;layer.dataset.mnDecoration='1';layer.setAttribute('aria-hidden','true');layer.style.setProperty('--surface-intensity',c.effectIntensity);layer.style.setProperty('--surface-color',c.effectColor);layer.style.setProperty('--surface-blur',c.effectBlur+'px');layer.style.setProperty('--surface-duration',Math.max(1,8/c.effectSpeed)+'s');
 const oldPosition=node.style.position,inside=!node.matches('img,svg,input,progress,textarea,select');if(global){layer.classList.add('mn-surface-screen');document.body.append(layer);}else if(inside){if(getComputedStyle(node).position==='static')node.style.position='relative';node.append(layer);}else{layer.classList.add('mn-surface-detached');document.body.append(layer);}
 let points;
 if(c.effect==='particles'&&node.matches('h1,h2,h3,p,strong,label,span')&&!global){const canvas=document.createElement('canvas'),rect=node.getBoundingClientRect();canvas.width=Math.min(900,Math.ceil(rect.width));canvas.height=Math.min(200,Math.ceil(rect.height));const ctx=canvas.getContext('2d',{willReadFrequently:true});if(ctx){const css=getComputedStyle(node);ctx.font=`${css.fontWeight} ${css.fontSize} ${css.fontFamily}`;ctx.textBaseline='middle';ctx.fillText(node.textContent.trim().slice(0,80),0,canvas.height/2);const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;points=[];for(let y=3;y<canvas.height;y+=4)for(let x=3;x<canvas.width;x+=4)if(data[(y*canvas.width+x)*4+3]>100)points.push([x,y]);}}
 const count=c.effect==='noise'||c.effect==='shimmer'?1:Math.min(32,c.effectDensity),animations=[];
 for(let i=0;i<count;i++){const dot=document.createElement('i');layer.append(dot);const x=(i*37+17)%97,y=(i*61+13)%97;dot.style.left=x+'%';dot.style.top=y+'%';dot.style.width=dot.style.height=c.effectSize*(.7+(i%4)*.2)+'px';dot.style.animationDelay=-(i%7)*.71+'s';if(points?.length){dot.style.left='0';dot.style.top='0';dot.style.width=dot.style.height='2px';dot.style.background='transparent';dot.style.boxShadow=points.filter((_,j)=>j%count===i).map(([x,y])=>`${x}px ${y}px 0 var(--surface-color)`).join(',');}if(c.effect==='neon'){dot.style.left=(i%4)*25+'%';dot.style.top=Math.floor(i/4)*25+'%';dot.style.width=dot.style.height='18%';}if(c.effect==='shimmer'||c.effect==='noise'){dot.style.cssText='';}}
 let timer,originalInk;
 const restoreInk=()=>{if(originalInk!==undefined){node.style.color=originalInk;originalInk=undefined;}};
 const quiet=()=>document.hidden||node.closest('.paused')||getComputedStyle(node).visibility==='hidden'||getComputedStyle(node).display==='none';
 function pulse(){if(quiet()||matchMedia('(prefers-reduced-motion: reduce)').matches)return;clearTimeout(timer);restoreInk();if(points?.length){originalInk=node.style.color;node.style.color='transparent';}for(const a of animations)a.cancel();animations.length=0;layer.dataset.active='1';const duration=Math.max(250,900/c.effectSpeed);for(const [i,dot]of [...layer.children].entries()){const a=dot.animate([{transform:'translate(0,0) scale(1)',opacity:.8},{transform:`translate(${Math.cos(i*2.4)*c.effectSize*2}px,${Math.sin(i*2.4)*c.effectSize*2}px) scale(.6)`,opacity:0}],{duration,fill:'both',easing:'ease-out'});animations.push(a);}timer=setTimeout(()=>{restoreInk();layer.dataset.active='0';for(const a of animations)a.cancel();animations.length=0;},duration);}
 if(c.effectTrigger!=='continuous'){layer.dataset.active='0';if(c.effectTrigger==='tap')node.addEventListener('click',pulse);}
 function align(){if(global||inside)return;const r=node.getBoundingClientRect();Object.assign(layer.style,{left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'});}
 const observer=new ResizeObserver(align);observer.observe(node);align();if(!inside&&!global)window.addEventListener('scroll',align,{passive:true,capture:true});
 const pause=()=>{const paused=quiet();layer.dataset.paused=String(paused);for(const a of animations)if(paused)a.pause();else if(a.playState==='paused')a.play();};document.addEventListener('visibilitychange',pause);pause();
 return {signature:JSON.stringify(c),trigger:c.effectTrigger,layer,node,pulse,pause,destroy(){clearTimeout(timer);restoreInk();observer.disconnect();document.removeEventListener('visibilitychange',pause);node.removeEventListener('click',pulse);window.removeEventListener('scroll',align,{capture:true});animations.forEach(a=>a.cancel());layer.remove();if(inside&&node.style.position==='relative'&&oldPosition!=='relative')node.style.position=oldPosition;}};
}
export function syncElementSurface(node,style){for(const [old,row]of rows)if(!old.isConnected){row.destroy();rows.delete(old);}const c=surfaceConfig(style),sig=JSON.stringify(c),old=rows.get(node);if(old?.signature===sig){old.pause();return;}old?.destroy();rows.delete(node);if(c.effect!=='none'&&rows.size<16)rows.set(node,make(node,c));}
export function syncScreenSurface(root,config,view){const c=surfaceConfig(config.screenEffects?.[view]),sig=JSON.stringify([view,c]);if(screen?.signature!==sig){screen?.destroy();screen=c.effect==='none'?null:make(root,c,true);if(screen)screen.signature=sig;}screen?.pause();}
export function triggerSurfaceEffects(root,event='answer'){for(const row of rows.values())if(root.contains(row.node)&&row.trigger===event)row.pulse();if(screen&&screen.trigger===event)screen.pulse();}
