// Shared decoration for every screen and component. Geometry stays untouched.
export const SURFACE_EFFECTS={none:'Bez efektu',noise:'Miękkie ziarno',particles:'Cząsteczki liter / iskry',neon:'Neonowa siatka',shimmer:'Płynny blask obrzeża',bokeh:'Bokeh',bubbles:'Bąble'};
export const SURFACE_FIELDS={effectIntensity:[0,1,.05,'Intensywność'],effectDensity:[1,32,1,'Liczba obiektów'],effectSpeed:[.05,3,.05,'Tempo'],effectSize:[2,360,2,'Wielkość (px)'],effectBlur:[0,32,.5,'Miękkość (px)'],effectTravel:[0,200,2,'Zasięg pływania (px)'],effectSizeVariation:[0,1,.05,'Różne wielkości'],effectColorShift:[0,180,5,'Różne kolory (°)']};
export const DEFAULT_SURFACE={effect:'none',effectIntensity:.7,effectDensity:12,effectSpeed:.5,effectSize:120,effectBlur:8,effectTravel:65,effectSizeVariation:.5,effectColorShift:70,effectColor:'#ffd4a3',effectTrigger:'continuous',effectLayer:'foreground'};
export function surfaceConfig(value={}){return {...DEFAULT_SURFACE,...value};}
export function surfacePreset(effect){return surfaceConfig({effect,...({bokeh:{effectSize:180,effectBlur:12,effectIntensity:.8,effectDensity:10},bubbles:{effectSize:90,effectDensity:16,effectIntensity:.8},noise:{effectSize:3,effectIntensity:.5,effectDensity:1},particles:{effectSize:5,effectDensity:24},shimmer:{effectIntensity:.75,effectBlur:12},neon:{effectIntensity:.9,effectColor:'#906eff'}}[effect]||{})});}
export function surfaceStack(value={}){return Array.isArray(value.surfaceEffects)?value.surfaceEffects.map(surfaceConfig):value.effect&&value.effect!=='none'?[surfaceConfig(value)]:[];}
export function validateSurface(value){if(value.surfaceEffects!==undefined){if(!Array.isArray(value.surfaceEffects)||value.surfaceEffects.length>4)throw Error('Maksymalnie cztery efekty na obiekt.');for(const row of value.surfaceEffects){if(!row||typeof row!=='object'||row.surfaceEffects)throw Error('Nieprawidłowy efekt.');validateSurface(row);}}const c=surfaceConfig(value);if(!Object.hasOwn(SURFACE_EFFECTS,c.effect)||!['foreground','background'].includes(c.effectLayer)||!['continuous','tap','answer'].includes(c.effectTrigger)||!/^#[0-9a-f]{6}$/i.test(c.effectColor))throw Error('Nieprawidłowy efekt powierzchni.');for(const [key,[min,max]]of Object.entries(SURFACE_FIELDS))if(!Number.isFinite(c[key])||c[key]<min||c[key]>max)throw Error('Sprawdź parametr efektu: '+key);if(!Number.isInteger(c.effectDensity))throw Error('Liczba obiektów musi być całkowita.');return c;}
const rows=new Map();let screen;let screenRoot,screenRootIsolation;
function styles(){if(document.querySelector('link[data-mn-surface-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.dataset.mnSurfaceCss='1';l.href=new URL('./surface-effects.css',import.meta.url).href;document.head.append(l);}
function make(node,value,global=false){
 styles();const c=surfaceConfig(value),layer=document.createElement('div');layer.className='mn-surface-layer mn-surface-'+c.effect;layer.dataset.mnDecoration='1';layer.dataset.layer=c.effectLayer;layer.setAttribute('aria-hidden','true');layer.style.setProperty('--surface-intensity',c.effectIntensity);layer.style.setProperty('--surface-color',c.effectColor);layer.style.setProperty('--surface-blur',c.effectBlur+'px');layer.style.setProperty('--surface-travel',c.effectTravel+'px');layer.style.setProperty('--surface-duration',Math.max(1,8/c.effectSpeed)+'s');
 const oldPosition=node.style.position,oldIsolation=node.style.isolation,inside=!node.matches('img,svg,input,progress,textarea,select');if(global){layer.classList.add('mn-surface-screen');if(c.effectLayer==='background'){layer.classList.add('mn-surface-background');node.prepend(layer);}else document.body.append(layer);}else if(inside){if(getComputedStyle(node).position==='static')node.style.position='relative';node.append(layer);}else{layer.classList.add('mn-surface-detached');document.body.append(layer);}
 if(!global&&inside&&c.effectLayer==='background')node.style.isolation='isolate';
 let points;
 if(c.effect==='particles'&&node.matches('h1,h2,h3,p,strong,label,span')&&!global){const canvas=document.createElement('canvas'),rect=node.getBoundingClientRect();canvas.width=Math.min(900,Math.ceil(rect.width));canvas.height=Math.min(200,Math.ceil(rect.height));const ctx=canvas.getContext('2d',{willReadFrequently:true});if(ctx){const css=getComputedStyle(node);ctx.font=`${css.fontWeight} ${css.fontSize} ${css.fontFamily}`;ctx.textBaseline='middle';ctx.fillText(node.textContent.trim().slice(0,80),0,canvas.height/2);const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;points=[];for(let y=3;y<canvas.height;y+=4)for(let x=3;x<canvas.width;x+=4)if(data[(y*canvas.width+x)*4+3]>100)points.push([x,y]);}}
 const count=c.effect==='noise'||c.effect==='shimmer'?1:Math.min(32,c.effectDensity),animations=[];
 for(let i=0;i<count;i++){const dot=document.createElement('i');layer.append(dot);const x=(i*37+17)%97,y=(i*61+13)%97;dot.style.left=x+'%';dot.style.top=y+'%';dot.style.width=dot.style.height=c.effectSize*(1-c.effectSizeVariation*.7+((i*29)%100)/100*c.effectSizeVariation*1.4)+'px';dot.style.setProperty('--dot-color',shiftColor(c.effectColor,((i*67)%101)/100*c.effectColorShift-c.effectColorShift/2));dot.style.setProperty('--dot-angle',((i*67)%360)+'deg');dot.style.marginLeft=dot.style.marginTop=(-c.effectSize/2)+'px';dot.style.animationDelay=-(i%7)*.71+'s';if(points?.length){dot.style.left='0';dot.style.top='0';dot.style.width=dot.style.height='2px';dot.style.background='transparent';dot.style.boxShadow=points.filter((_,j)=>j%count===i).map(([x,y])=>`${x}px ${y}px 0 var(--surface-color)`).join(',');}if(c.effect==='neon'){dot.style.left=(i%4)*25+'%';dot.style.top=Math.floor(i/4)*25+'%';dot.style.width=dot.style.height='18%';}if(c.effect==='shimmer'||c.effect==='noise'){dot.style.cssText='';}}
 let timer,originalInk;
 const restoreInk=()=>{if(originalInk!==undefined){node.style.color=originalInk;originalInk=undefined;}};
 const quiet=()=>document.hidden||node.closest('.paused')||getComputedStyle(node).visibility==='hidden'||getComputedStyle(node).display==='none';
 function pulse(){if(quiet()||matchMedia('(prefers-reduced-motion: reduce)').matches)return;clearTimeout(timer);restoreInk();if(points?.length){originalInk=node.style.color;node.style.color='transparent';}for(const a of animations)a.cancel();animations.length=0;layer.dataset.active='1';const duration=Math.max(250,900/c.effectSpeed);for(const [i,dot]of [...layer.children].entries()){const a=dot.animate([{transform:'translate(0,0) scale(1)',opacity:.8},{transform:`translate(${Math.cos(i*2.4)*c.effectSize*2}px,${Math.sin(i*2.4)*c.effectSize*2}px) scale(.6)`,opacity:0}],{duration,fill:'both',easing:'ease-out'});animations.push(a);}timer=setTimeout(()=>{restoreInk();layer.dataset.active='0';for(const a of animations)a.cancel();animations.length=0;},duration);}
 if(c.effectTrigger!=='continuous'){layer.dataset.active='0';if(c.effectTrigger==='tap')node.addEventListener('click',pulse);}
 function align(){if(global||inside)return;const r=node.getBoundingClientRect();Object.assign(layer.style,{left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'});}
 const observer=new ResizeObserver(align);observer.observe(node);align();if(!inside&&!global)window.addEventListener('scroll',align,{passive:true,capture:true});
 const pause=()=>{const paused=quiet();layer.dataset.paused=String(paused);for(const a of animations)if(paused)a.pause();else if(a.playState==='paused')a.play();};document.addEventListener('visibilitychange',pause);pause();
 return {signature:JSON.stringify(c),trigger:c.effectTrigger,layer,node,pulse,pause,destroy(){clearTimeout(timer);restoreInk();observer.disconnect();document.removeEventListener('visibilitychange',pause);node.removeEventListener('click',pulse);window.removeEventListener('scroll',align,{capture:true});animations.forEach(a=>a.cancel());layer.remove();if(inside&&node.style.isolation==='isolate')node.style.isolation=oldIsolation;if(inside&&node.style.position==='relative'&&oldPosition!=='relative')node.style.position=oldPosition;}};
}
function bundle(node,style,global=false){const configs=surfaceStack(style).filter(c=>c.effect!=='none'),list=configs.map(c=>make(node,c,global));return {signature:JSON.stringify(configs),node,pause(){list.forEach(r=>r.pause());},pulse(event){list.filter(r=>r.trigger===event).forEach(r=>r.pulse());},destroy(){[...list].reverse().forEach(r=>r.destroy());}};}
export function syncElementSurface(node,style){for(const [old,row]of rows)if(!old.isConnected){row.destroy();rows.delete(old);}const configs=surfaceStack(style).filter(c=>c.effect!=='none'),sig=JSON.stringify(configs),old=rows.get(node);if(old?.signature===sig){old.pause();return;}old?.destroy();rows.delete(node);if(configs.length&&rows.size<16)rows.set(node,bundle(node,style));}
export function syncScreenSurface(root,config,view){const value=config.screenEffects?.[view]||{},configs=surfaceStack(value).filter(c=>c.effect!=='none'),sig=JSON.stringify([view,configs]);if(screen?.signature!==sig){screen?.destroy();if(screenRoot)screenRoot.style.isolation=screenRootIsolation;screenRoot=root;screenRootIsolation=root.style.isolation;root.style.isolation='isolate';screen=configs.length?bundle(root,value,true):null;if(screen)screen.signature=sig;}screen?.pause();}
export function triggerSurfaceEffects(root,event='answer'){for(const row of rows.values())if(root.contains(row.node))row.pulse(event);screen?.pulse(event);}
function shiftColor(hex,shift){const rgb=[1,3,5].map(n=>parseInt(hex.slice(n,n+2),16)/255),max=Math.max(...rgb),min=Math.min(...rgb),d=max-min,l=(max+min)/2;let h=0,s=0;if(d){s=d/(1-Math.abs(2*l-1));h=max===rgb[0]?((rgb[1]-rgb[2])/d)%6:max===rgb[1]?(rgb[2]-rgb[0])/d+2:(rgb[0]-rgb[1])/d+4;h*=60;}return `hsl(${(h+shift+360)%360} ${s*100}% ${l*100}%)`;}
