import {structureCatalog,PART_BY_ID,LEVEL_NAMES,viewParts} from '../shared/structure-model.mjs';
import {revealResult,settleResult} from '../ortografia/result-motion.mjs';
import {progressParticles} from '../ortografia/result-screen.mjs';
import {BLOCKS,BLUE_THEME,FAMILY_NAMES,familyTokens} from '../shared/building-blocks.mjs';
import {ATOMS,DEFAULT_RECIPES,recipeStyle} from '../shared/component-recipes.mjs';
import {createJellyV4} from '../shared/jelly-v4.mjs';
import {createContinueDrag} from '../spelling/continue-drag.mjs';
import {DURATIONS} from '../game.mjs';
import {WORD_LIMITS} from '../spelling/round.mjs';
import {ELEMENT_MOTIONS,syncElementMotion} from '../shared/element-motion.mjs';
import {declarations,iconSVG,VISUAL_FIELDS,visualValue} from '../shared/element-system.mjs';
import {surfaceEditor,editSurface} from './surface-editor.mjs';
import {surfaceStack,surfacePreset,syncElementSurface} from '../shared/surface-effects.mjs';
import {html,FIELD_LABELS,rangeFor,savedMarker} from './preview-model.mjs';
import {configCSS,variables,FONT_NAMES} from './model.mjs';
import {tokenBounds} from './validation.mjs';
const defaults=await fetch(new URL('recipe-defaults.json',import.meta.url)).then(r=>r.json());
export const SEGMENTED_EXAMPLES={scope:['Wszystko','Kategorie','Dyktando'],level:['Wszystkie','Podstawowe','Trudne'],time:DURATIONS.map(n=>n/60+' min'),count:WORD_LIMITS.map(n=>n+' słów'),language:['PL','EN']};
export const MAX_OPTIONS=Math.max(...Object.values(SEGMENTED_EXAMPLES).map(rows=>rows.length));
const roles={body:'Tekst',ui:'Kontrolki',display:'Tytuły',flag:'Flagi'};
const styleDefaults={margin:0,marginTop:0,marginBottom:0,marginLeft:0,marginRight:0,padding:0,gap:8,shadowY:6,shadowBlur:18,shadowOpacity:.12,opacity:1,stateDuration:260,stateDistance:6,animationDuration:1600,animationDistance:6};
export class LiveRecipes{
 constructor(owner){this.owner=owner;this.block='jelly';this.atom='';this.part='control-jelly';this.mode='default';this.example='level';this.count=3;this.choice=0;this.percent=72;this.variant='result';this.state='idle';this.spacing=false;this.groups=new Map();window.addEventListener('message',e=>{const frame=this.workspace.querySelector('.library-live-frame');if(e.origin!==location.origin||e.source!==frame?.contentWindow||e.data?.channel!=='mala-nauka-studio')return;if(e.data.type==='ready'){this.sendDesign();if(frame.dataset.selector)frame.contentWindow.postMessage({channel:'mala-nauka-studio',type:'isolate',selector:frame.dataset.selector},location.origin);}if(e.data.type==='inventory')this.owner.acceptInventory?.(frame.dataset.view,e.data.items||[]);});}
 get config(){return this.owner.getDesign().config;}
 catalog(){const inventories=this.owner.getInventories?.()||new Map();if(this.cachedCatalog&&this.catalogSnapshot.size===inventories.size&&[...this.catalogSnapshot].every(([id,row])=>inventories.get(id)===row))return this.cachedCatalog;this.catalogSnapshot=new Map(inventories);return this.cachedCatalog=structureCatalog(this.owner.registry,inventories);}
 get record(){return this.catalog().find(p=>p.id===this.part);}
 get meta(){const p=this.record;return p?{...BLOCKS[p.block],...p,recipe:p.id,groups:BLOCKS[p.block]?.groups||[],parts:p.children}:BLOCKS[this.block]||{recipe:this.part,name:this.part,level:'atom',kind:'container',groups:[],parts:[]};}
 selectPart(id){this.atom='';this.part=id;const p=this.catalog().find(p=>p.id===id);this.atom=p?.atom||'';this.block=p?.block||'generic';this.mode='default';this.percent=this.block==='slider'?0:72;}
 sendDesign(){const frame=this.workspace.querySelector('.library-live-frame');frame?.contentWindow?.postMessage({channel:'mala-nauka-studio',type:'design',...this.owner.getDesign()},location.origin);}
 get workspace(){return this.owner.workspace;}
 path(group,key){return this.mode==='default'?`tokens.${group}.${key}`:`familyTokens.${this.mode}.${group}.${key}`;}
 stylePath(key){return this.mode==='default'?`elementStyles.${this.meta.recipe}.${key}`:`familyStyles.${this.mode}.${this.meta.recipe}.${key}`;}
 write(path,value){this.owner.editLibrary(path,value);}
 style(){return visualValue(this.config,'',{id:'sample',kind:this.meta.kind||'sample',recipe:this.meta.recipe,mode:this.mode});}
 control(path,label,value,base,min,max,step=1,unit=''){
 return `<div class=control><div class=control-top><label>${html(label)}</label><span class=control-value><input type=number data-live-value="${path}" min=${min} max=${max} step=${step} value=${value}><span>${unit}</span></span></div><div class=range-wrap><input type=range data-live-value="${path}" min=${min} max=${max} step=${step} value=${value}><span class=saved-mark style="--saved-position:${savedMarker(base,min,max)/100}"></span></div><div class=saved-value><span>Domyślnie: <b>${base} ${unit}</b></span><button type=button data-live-reset="${path}" data-default=${base}>Przywróć</button></div></div>`;
 }
 select(path,label,value,choices){return `<label class=form-field><span>${html(label)}</span><select data-live-field="${path}">${Object.entries(choices).map(([id,name])=>`<option value="${id}" ${value===id?'selected':''}>${html(name)}</option>`).join('')}</select></label>`;}
 group(id,name,content,open=false){return `<details data-live-group=${id} ${this.groups.get(id)??open?'open':''}><summary>${name}</summary><div class=recipe-control-grid>${content}</div></details>`;}
 render(){
 const c=this.config,recipes=c.recipes||DEFAULT_RECIPES,uses=id=>this.owner.registry.views.filter(v=>v.components.includes(id)),r=this.atom?recipes[this.atom]:null;
 const catalog=this.catalog(),row=p=>`<button class="recipe-library-row ${!this.atom&&this.part===p.id?'active':''}" data-live-part="${html(p.id)}">${iconSVG(p.kind==='image'?'screen':p.level==='atom'?'square':'layers')}<span><strong>${html(p.name)}</strong><small>${LEVEL_NAMES[p.level]} · ${p.uses.length} widoków</small></span></button>`;
 const atoms=catalog.filter(p=>p.level==='atom'&&!p.atom),groups=catalog.filter(p=>p.level==='group');
 const list=(name,rows,open=false)=>`<details ${open?'open':''}><summary>${name} · ${rows.length}</summary>${rows.map(row).join('')}</details>`;
 const library=`<aside class="panel recipe-library"><header><span class=section-kicker>BIBLIOTEKA KLOCKÓW</span><h3>Atomy → grupy → rodziny</h3></header>${list('Atomy · sterowanie',atoms.filter(p=>['button','toggle','key','meter','icon'].includes(p.kind)),true)}${list('Atomy · grafika i podkłady',atoms.filter(p=>['image','background','container'].includes(p.kind)))}<details><summary>Atomy · tekst i fonty</summary>${Object.entries(ATOMS).map(([id,a])=>`<button class="recipe-library-row ${this.atom===id?'active':''}" data-live-part=text-role-${id}><span class=atom-mark>Aa</span><span><strong>${a.name}</strong><small>Tekst + font</small></span></button>`).join('')}${atoms.filter(p=>p.kind==='text').map(row).join('')}</details>${list('Grupy · składniki',groups)}${list('Rodziny · całe widoki',catalog.filter(p=>p.level==='family'))}</aside>`;
 if(this.record?.level==='family')return this.renderView(library);

 const family=this.block==='generic'?'':this.select('family','Paleta trybu',this.mode,FAMILY_NAMES),meta=this.atom?{name:ATOMS[this.atom].name,level:'atom'}:this.meta;
 let controls='',parts='';
 if(this.atom){
  controls=this.group('font','Font i tekst',this.select(`recipes.${this.atom}.role`,'Font używany w grze',r.role,Object.fromEntries(Object.entries(roles).map(([role,name])=>[role,`${name} · ${FONT_NAMES[c.typography[role]]}`])))+['size','weight','lineHeight','gap','padding'].map(key=>{const bounds={size:[10,48,.5,'px'],weight:[300,900,100,''],lineHeight:[1,2,.05,''],gap:[0,40,1,'px'],padding:[0,24,1,'px']}[key];return this.control(`recipes.${this.atom}.${key}`,{size:'Rozmiar',weight:'Grubość',lineHeight:'Interlinia',gap:'Odstęp',padding:'Odstęp wewnątrz'}[key],r[key],DEFAULT_RECIPES[this.atom][key],...bounds);}).join(''),true)+`<label><input type=checkbox data-live-enabled ${r.enabled?'checked':''}> Stosuj przepis we wszystkich użyciach</label>`;
  parts=`<li>Treść tekstu</li><li>Font: ${FONT_NAMES[c.typography[r.role]]}</li><li>Rozmiar, grubość, interlinia</li><li>Odstępy</li>`;
 }else{
  for(const group of this.meta.groups){const t=familyTokens(c,this.mode,group);if(!t)continue;controls+=this.group(group,{jelly:'Geometria i przejście jelly',slider:'Tor i uchwyt',sliderWrong:'Po błędzie',sliderResult:'Nowa runda',resultText:'Animowany tekst'}[group]||'Geometria i zachowanie',Object.entries(t).filter(([,v])=>typeof v==='number').map(([key,value])=>{const [min,max]=tokenBounds(group,key),[,,step,unit]=rangeFor(group,key);return this.control(this.path(group,key),FIELD_LABELS[key]||key,value,this.mode==='default'?(defaults.tokens[group]?.[key]??value):(c.tokens[group]?.[key]??value),min,max,step,unit);}).join(''),group===this.block);}
  const st=this.style();
  if(this.block==='generic')controls+=this.group('geometry','Rozmiar i pozycja',['width','height','padding','gap','radius','fontSize','opacity','offsetX','offsetY'].map(k=>this.control(this.stylePath(k),VISUAL_FIELDS[k][2],st[k]??({width:0,height:0,fontSize:20,radius:0,offsetX:0,offsetY:0,...styleDefaults}[k]||0),styleDefaults[k]??0,...VISUAL_FIELDS[k].slice(0,2),k==='opacity'?.05:1)).join(''),true);
  if(this.meta.kind==='text')controls+=this.group('fontRole','Font',this.select(this.stylePath('fontRole'),'Font używany w grze',st.fontRole||'body',Object.fromEntries(Object.entries(roles).map(([role,name])=>[role,name+' · '+FONT_NAMES[c.typography[role]]]))));
  if(['image','background'].includes(this.meta.kind))controls+=this.group('asset','Grafika i kadr',this.select(this.stylePath('asset'),'Asset',st.asset||this.meta.asset||'',{'':'Grafika z widoku',...Object.fromEntries((this.owner.getDesign().assets?.assets||[]).filter(a=>/\.(webp|png|jpg|svg)$/.test(a.path)).map(a=>[a.path,a.path.replace('assets/','')]))})+this.select(this.stylePath('fit'),'Dopasowanie',st.fit||'cover',{cover:'Wypełnij',contain:'Cały obrazek'})+['imageScale','imageX','imageY'].map(k=>this.control(this.stylePath(k),VISUAL_FIELDS[k][2],st[k]??(k==='imageScale'?1:50),k==='imageScale'?1:50,...VISUAL_FIELDS[k].slice(0,2),.05)).join(''));
  controls+=this.group('elementColors','Kolory tła i tekstu',[['background','Tło','#ffffff'],['textColor','Tekst / ikona','#09043f']].map(([key,label,fallback])=>`<label class=form-field><span>${label}</span><input type=color data-live-field="${this.stylePath(key)}" value="${st[key]?.slice(0,7)||fallback}"></label>`).join(''));
  controls+=this.group('states','Stany i przejścia',this.select(this.stylePath('idleAnimation'),'Nieaktywny',st.idleAnimation||'none',ELEMENT_MOTIONS)+this.select(this.stylePath('activeAnimation'),'Aktywny',st.activeAnimation||'none',ELEMENT_MOTIONS)+this.select(this.stylePath('enterAnimation'),'Wejście',st.enterAnimation||'none',ELEMENT_MOTIONS)+this.select(this.stylePath('exitAnimation'),'Wyjście',st.exitAnimation||'none',ELEMENT_MOTIONS)+['stateDuration','stateDistance','animationDuration','animationDistance'].map(k=>this.control(this.stylePath(k),VISUAL_FIELDS[k][2],st[k]??styleDefaults[k],styleDefaults[k],...VISUAL_FIELDS[k].slice(0,2),1,k.includes('Duration')?'ms':'px')).join(''));
  if(this.block==='jelly')controls+=this.group('optionMotion','Animacja wybranej etykiety',this.select('elementStyles.jelly-option.activeAnimation','Aktywny wybór',c.elementStyles?.['jelly-option']?.activeAnimation||'none',ELEMENT_MOTIONS)+this.select('elementStyles.jelly-option.idleAnimation','Nieaktywny wybór',c.elementStyles?.['jelly-option']?.idleAnimation||'none',ELEMENT_MOTIONS));
  controls+=this.group('spacing','Odstępy wewnętrzne i zewnętrzne',['padding','gap','margin'].map(k=>this.control(this.stylePath(k),VISUAL_FIELDS[k][2],st[k]??styleDefaults[k],styleDefaults[k],0,120,1,'px')).join('')+this.group('sides','Każdy bok osobno',['paddingTop','paddingBottom','paddingLeft','paddingRight','marginTop','marginBottom','marginLeft','marginRight'].map(k=>this.control(this.stylePath(k),VISUAL_FIELDS[k][2],st[k]??0,0,0,120,1,'px')).join('')));
  controls+=this.group('shadow','Cień i przezroczystość',['shadowY','shadowBlur','shadowOpacity','opacity'].map(k=>this.control(this.stylePath(k),VISUAL_FIELDS[k][2],st[k]??styleDefaults[k],styleDefaults[k],...VISUAL_FIELDS[k].slice(0,2),(k.includes('Opacity')||k==='opacity')?.01:1)).join(''));
  controls+=this.group('surface','Efekty powierzchni',surfaceEditor(st,this.surfaceIndex||0));
  if(['slider','progress'].includes(this.block))controls+=`<label class=form-field><span>Kolor pełnego paska</span><input type=color data-live-field="${this.stylePath('completeColor')}" value="${st.completeColor|| (this.mode==='default'?BLUE_THEME.accent:c.themes[this.mode].accent)}"></label>`;
  controls+=this.group('palette','Kolory rodziny',Object.entries(this.mode==='default'?(c.defaultTheme||BLUE_THEME):c.themes[this.mode]).map(([key,value])=>`<label class=form-field><span>${{accent:'Wiodący',activeInk:'Aktywny tekst',idleInk:'Nieaktywny tekst'}[key]||key}</span><input type=color data-live-field="${this.mode==='default'?'defaultTheme':'themes.'+this.mode}.${key}" value="${value.slice(0,7)}"></label>`).join(''));
  parts=(this.meta.parts||[]).map(id=>{const p=catalog.find(p=>p.id===id);return `<li><button class=structure-link data-live-part="${html(id)}">${html(p?.name||id)} <small>${LEVEL_NAMES[p?.level]||'Część'}</small></button></li>`;}).join('')||'<li>Samodzielny atom. Pozostałe części są w grupach, które go używają.</li>';if(this.meta.inherits)parts=`<li><button class=structure-link data-live-part=${this.meta.inherits}>Dziedziczy: ${html(PART_BY_ID[this.meta.inherits]?.name||this.meta.inherits)}</button></li>`+parts;
 }
 let example='';
 if(['jelly','toggle'].includes(this.block)&&!this.atom)example=this.select('example','Przykład z gry',this.example,Object.fromEntries(Object.keys(SEGMENTED_EXAMPLES).map(id=>[id,{scope:'Zakres: Kategorie / Dyktando',level:'Poziomy',time:'Czas',count:'Liczba słów',language:'Język'}[id]])))+this.select('count','Liczba opcji',String(this.count),Object.fromEntries(Array.from({length:MAX_OPTIONS-1},(_,i)=>[i+2,String(i+2)])));
 if(this.block==='slider'&&!this.atom)example=this.select('variant','Zastosowanie',this.variant,{wrong:'Po błędzie',result:'Nowa runda'});
 if(['slider','progress'].includes(this.block)&&!this.atom)example+=`<label class=form-field><span>Symulacja · <output id=live-percent>${this.percent}%</output></span><input type=range id=live-progress min=0 max=100 value=${this.percent}></label><button class=quiet-button data-live-complete>100% · zakończenie</button><button class=quiet-button data-live-restart>Od początku</button>`;
 const used=this.atom?this.owner.registry.views.filter(v=>ATOMS[this.atom].parents.some(p=>v.components.includes(p))):this.owner.registry.views.filter(v=>this.record?.uses.some(u=>u.view===v.id));
 return `<div class=recipe-grid data-live-library>${library}<section class="panel recipe-editor"><header class=recipe-editor-head><div><span class=section-kicker>${html(LEVEL_NAMES[meta.level]||meta.level).toUpperCase()}</span><h3>${meta.name}</h3></div></header><div class=live-example-tools>${family}${example}</div><div class="family-recipe-sample live-recipe-stage" id=live-stage></div><button class=quiet-button data-live-spacing aria-pressed=${this.spacing}>${iconSVG('spacer')} Pokaż odstępy wewnętrzne i zewnętrzne</button><div class=live-recipe-controls>${controls}</div></section><aside class="panel recipe-context"><h3>Co tworzy ten element?</h3><ul class=live-parts>${parts}</ul><details open><summary>Grupy i zastosowania</summary>${!this.atom&&this.block==='card'?'<p>Podkład jest atomem. Grupa ustawień łączy go z numerem, tekstem, jelly i przełącznikiem.</p>':''}${catalog.filter(p=>p.children.includes(this.part)).map(p=>`<button class=structure-link data-live-part="${html(p.id)}">${LEVEL_NAMES[p.level]} · ${html(p.name)}</button>`).join('')}</details><details><summary>Użycia · ${used.length}</summary><div class=recipe-views>${used.map(v=>`<button class=small-button data-live-use=${v.id}>${html(v.name)}</button>`).join('')}</div></details></aside></div>`;
 }
 renderView(library){const v=this.owner.registry.views.find(v=>v.id===this.record.view),parts=viewParts(v,this.owner.getInventories?.().get(v.id));const branch=rows=>rows.map(p=>`<div class=flow-part-row><button class=structure-link data-live-part="${html(p.recipe)}"><small>${LEVEL_NAMES[p.level]}</small>${html(p.name)}</button>${p.children.length?`<details><summary>W środku · ${p.children.length}</summary>${branch(p.children)}</details>`:''}</div>`).join('');return `<div class=recipe-grid data-live-library>${library}<section class="panel recipe-editor"><span class=section-kicker>RODZINA · WIDOK</span><h3>${html(v.name)}</h3><div id=live-stage class="family-recipe-sample library-view-stage"></div><button class=quiet-button data-live-use=${v.id}>Edytuj układ w Komponentach</button></section><aside class="panel recipe-context"><h3>Grupy i atomy tego widoku</h3>${branch(parts)}</aside></div>`;}
 mountRuntime(stage){const record=this.record,use=record?.uses[0],view=this.owner.registry.views.find(v=>v.id===(record?.view||use?.view));if(!view){stage.innerHTML='<p>Otwórz użycie w Komponentach, aby zebrać stan tej części.</p>';return;}const url=new URL(view.route,location.origin);url.search=new URLSearchParams({studio:'1',mode:view.mode,screen:view.screen,state:view.state,viewId:view.id});stage.innerHTML=`<iframe class=library-live-frame title="${html(record.name)} · prawdziwy widok" src="${url.href}" data-view="${view.id}" ${record.level!=='family'?`data-selector="${html(use?.selector||record.selector)}"`:''}></iframe>`;stage.classList.toggle('library-view-stage',record.level==='family');}

 mount(){
 if(this.workspace.querySelector('.library-live-frame')&&this.record?.level!=='family'){this.sendDesign();return;}
 this.drag?.destroy();this.drag=null;this.observer?.disconnect();const stage=this.workspace.querySelector('#live-stage');if(!stage)return;
 settleResult(stage);
 if(this.record?.level==='family'){this.mountRuntime(stage);return;}
 const config=this.config,theme=this.mode==='default'?(config.defaultTheme||BLUE_THEME):config.themes[this.mode],t=familyTokens(config,this.mode,this.block),st=this.atom?{}:this.style();
 stage.classList.toggle('show-spacing',this.spacing);stage.innerHTML=`<style>${configCSS(config)}</style><div class="ds-component-stage live-component" data-mode=${this.mode} style="${variables(theme,'--ds-theme')}${variables(config.familyTokens?.[this.mode]||{})}"><div class=live-margin><div id=live-sample ></div></div></div>`;
 const sample=stage.querySelector('#live-sample');
 if(this.atom){const r=config.recipes?.[this.atom]||DEFAULT_RECIPES[this.atom];sample.style.cssText=recipeStyle(r);if(this.atom==='numberText')sample.innerHTML='<span class=live-number-text><span class=step-dot>1</span><span>Co ćwiczymy?</span></span>';else sample.textContent='Małe kroki, wielkie odkrycia';}
 else if(this.block==='generic'){this.mountRuntime(stage);return;}
 else if(['jelly','toggle'].includes(this.block)){
  const values=SEGMENTED_EXAMPLES[this.example];const rows=Array.from({length:this.count},(_,i)=>values[i]||'Opcja '+(i+1));this.choice=Math.min(this.choice,rows.length-1);
  sample.innerHTML=`<div class=ds-jelly><i class=live-jelly-indicator></i>${rows.map((label,i)=>`<label data-ds-element="sample-option-${i}" data-ds-kind=text data-ds-recipe=jelly-option><input type=radio name=live-jelly value=${i} ${i===this.choice?'checked':''}><span>${html(label)}</span></label>`).join('')}</div>`;
  const jelly=createJellyV4({indicatorSelector:'.live-jelly-indicator',getTokens:()=>familyTokens(this.config,this.mode,'jelly')}),node=sample.firstElementChild;
  if(this.block==='toggle')node.style.cssText=`width:${t.width}px;height:${t.height}px;`;
  const choose=index=>{this.choice=index;node.querySelectorAll('input').forEach((i,n)=>i.checked=n===index);jelly.update(node,index,{animate:true});for(const label of node.querySelectorAll('label'))syncElementMotion(label,visualValue(this.config,'',{id:label.dataset.dsElement,kind:'text',recipe:'jelly-option',mode:this.mode}));};
  node.addEventListener('change',()=>choose(+node.querySelector('input:checked').value));let suppress=0;
  jelly.setupDrag(node,{getActiveIndex:()=>this.choice,commitIndex:choose,captureOnDrag:true,suppressClick:ms=>suppress=performance.now()+ms});node.addEventListener('click',e=>{if(performance.now()<suppress){e.preventDefault();e.stopPropagation();}},true);jelly.update(node,this.choice,{animate:false});
  this.observer=new ResizeObserver(()=>jelly.update(node,this.choice,{animate:false}));this.observer.observe(node);
 }else if(this.block==='button'||this.block==='answer'){
  sample.innerHTML=`<button class="${this.block==='button'?'start-button':'recipe-answer'}" data-live-press aria-pressed=false>Wybierz mnie</button><output class=live-state-label>Nieaktywny</output>`;const button=sample.querySelector('button');if(this.block==='answer')button.style.cssText=`height:${t.height}px;border-radius:${t.radius}px;font-size:${t.fontSize}px;`;button.addEventListener('click',()=>{const active=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',active);button.classList.toggle('selected',active);sample.querySelector('output').textContent=active?'Aktywny':'Nieaktywny';syncElementMotion(button,this.style());});
 }else if(this.block==='card')sample.innerHTML=`<article class=recipe-live-card style="border-radius:${t.radius}px;padding:${t.paddingTop}px ${t.paddingX}px ${t.paddingBottom}px;border-width:${t.borderWidth}px"><span>1</span><div><b>Co ćwiczymy?</b><small>Podkład + numer + tekst</small></div></article>`;
 else if(this.block==='slider'){
  sample.innerHTML=`<div class="recipe-action-rail ${this.variant==='wrong'?'spelling':'result'}-continue-rail" role=slider tabindex=0 aria-label="Slider akcji" aria-valuemin=0 aria-valuemax=100 aria-valuenow=0 style="height:${t.height}px;border-radius:${t.radius}px"><span class=continue-handle style="width:${t.handleSize}px;height:${t.handleSize}px">${iconSVG('arrow')}</span><span class=continue-copy>Przesuń, aby kontynuować</span><span class=continue-done>Gotowe ✓</span></div>`;
  this.drag=createContinueDrag(sample.firstElementChild,{variant:this.variant,getTokens:group=>familyTokens(this.config,this.mode,group),canContinue:()=>true,onComplete:()=>{this.percent=100;this.workspace.querySelector('#live-progress').value=100;this.workspace.querySelector('#live-percent').value='100%';}});if(this.percent)this.drag.setProgress(this.percent/100);
 }else sample.innerHTML=`<div class="result-v4 recipe-progress-scene"><div class="round-progress recipe-progress" role=progressbar aria-valuemin=0 aria-valuemax=100 aria-valuenow=${this.percent} style="height:${t.height}px;border-radius:${t.radius}px"><span class=round-progress-fill data-percent=${this.percent} style="width:${this.percent}%;background:var(--ds-complete-color,var(--ds-theme-accent))"><span class=round-progress-cap></span>${progressParticles(this.percent)}</span></div><output><span data-count=${this.percent} data-reel=percent>${this.percent}</span>%</output></div>`;
 if(!this.atom){const primitive=this.block==='progress'?sample.querySelector('.round-progress'):sample.firstElementChild;primitive.dataset.dsElement='sample';primitive.dataset.dsKind=this.meta.kind||'container';primitive.dataset.dsRecipe=this.meta.recipe;primitive.style.cssText+=';'+declarations(st);syncElementMotion(primitive,st);syncElementSurface(primitive,st);}
 }
 handle(e){if(!this.workspace.querySelector('[data-live-library]'))return false;const n=e.target,b=n.closest('button');
 if(e.type==='click'&&b?.dataset.livePart){this.selectPart(b.dataset.livePart);this.refresh();return true;}
 if(e.type==='click'&&b?.dataset.liveUse){const use=this.record?.uses.find(u=>u.view===b.dataset.liveUse);this.owner.openElement?.(b.dataset.liveUse,use?.selector);return true;}
 if(e.type==='click'&&(b?.dataset.liveBlock||b?.dataset.liveAtom)){this.atom=b.dataset.liveAtom||'';this.block=b.dataset.liveBlock||this.block;this.percent=this.block==='slider'?0:72;this.refresh();return true;}
 if(e.type==='click'&&b?.dataset.liveReset){this.write(b.dataset.liveReset,(this.mode!=='default'&&b.dataset.liveReset.startsWith('family'))||(this.meta.inherits&&b.dataset.liveReset.startsWith('elementStyles.'))?undefined:Number(b.dataset.default));this.refresh();return true;}
 if(e.type==='click'&&b?.hasAttribute('data-live-spacing')){this.spacing=!this.spacing;this.workspace.querySelector('#live-stage').classList.toggle('show-spacing',this.spacing);b.setAttribute('aria-pressed',this.spacing);return true;}
 if(e.type==='click'&&(b?.hasAttribute('data-live-complete')||b?.hasAttribute('data-live-restart'))){this.percent=b.hasAttribute('data-live-complete')?100:0;this.mount();this.workspace.querySelector('#live-progress').value=this.percent;this.workspace.querySelector('#live-percent').value=this.percent+'%';if(this.block==='progress'&&this.percent===100)revealResult(this.workspace.querySelector('#live-stage'),0,{progress:familyTokens(this.config,this.mode,'progress'),resultText:familyTokens(this.config,this.mode,'resultText')});return true;}
 if(e.type==='input'&&n.id==='live-progress'){this.percent=+n.value;this.workspace.querySelector('#live-percent').value=this.percent+'%';if(this.drag)this.drag.setProgress(this.percent/100);else this.mount();return true;}
 if(e.type==='input'&&n.dataset.liveValue){const value=+n.value;if(!Number.isFinite(value)||value<+n.min||value>+n.max)return true;this.write(n.dataset.liveValue,value);if(this.atom)this.write(`recipes.${this.atom}.enabled`,true);for(const other of this.workspace.querySelectorAll('[data-live-value]'))if(other!==n&&other.dataset.liveValue===n.dataset.liveValue)other.value=value;this.mount();return true;}
 if(e.type==='change'&&n.dataset.liveField){const path=n.dataset.liveField;if(path==='family')this.mode=n.value;else if(path==='example'){this.example=n.value;this.count=SEGMENTED_EXAMPLES[this.example].length;}else if(path==='count')this.count=+n.value;else if(path==='variant'){this.variant=n.value;this.percent=0;}else{const prior=path.split('.').reduce((v,k)=>v?.[k],this.config);this.write(path,n.value===''?undefined:n.type==='color'&&typeof prior==='string'&&prior.length===9?n.value+prior.slice(7):n.value);if(this.atom){const r=this.config.recipes?.[this.atom]||DEFAULT_RECIPES[this.atom];this.owner.applyRecipe(this.atom,{...r,enabled:true});}}this.refresh();return true;}
 if(e.type==='change'&&n.hasAttribute('data-live-enabled')){const r=this.config.recipes?.[this.atom]||DEFAULT_RECIPES[this.atom];this.owner.applyRecipe(this.atom,{...r,enabled:n.checked});return true;}
 if(e.type==='click'&&(b?.hasAttribute('data-surface-add')||b?.hasAttribute('data-surface-remove')||b?.dataset.surfaceSelect!==undefined)){const rows=surfaceStack(this.style());if(b.hasAttribute('data-surface-add')&&rows.length<4){rows.push(surfacePreset('bokeh'));this.surfaceIndex=rows.length-1;this.write(this.stylePath('surfaceEffects'),rows);}else if(b.hasAttribute('data-surface-remove')){rows.splice(this.surfaceIndex||0,1);this.surfaceIndex=0;this.write(this.stylePath('surfaceEffects'),rows);}else this.surfaceIndex=+b.dataset.surfaceSelect;this.refresh();return true;}
 if(n.dataset.surfaceField){if(e.type==='change'||e.type==='input'){const next=editSurface(this.style(),this.surfaceIndex||0,n.dataset.surfaceField,n.type==='number'||n.type==='range'?+n.value:n.value);this.write(this.stylePath('surfaceEffects'),next);if(e.type==='change'&&n.type!=='range'&&n.type!=='number')this.refresh();else this.mount();}return true;}
 return false;
 }
 leave(){this.drag?.destroy();this.observer?.disconnect();const stage=this.workspace.querySelector('#live-stage');if(stage)settleResult(stage);}
 refresh(){for(const d of this.workspace.querySelectorAll('[data-live-group]'))this.groups.set(d.dataset.liveGroup,d.open);this.owner.render();}
}
