import {clone,get,set,diff,changedViews,validateConfig,FONT_IDS,FONT_NAMES,FONT_FILES} from './model.mjs';
import {GitClient,mergeDraft,BRANCH,REPOSITORY} from './git-client.mjs';
import {applyDesign,designReady} from '../shared/design-runtime.mjs';
import {configureAssets,assetUrl,loadWords} from '../shared/asset-loader.mjs';
await designReady;
const read=async path=>{const response=await fetch(new URL(path,import.meta.url));if(!response.ok)throw Error(`Nie udało się wczytać ${path}.`);return response.json();};
const [initial,registry,initialAssets,audit,words]=await Promise.all([read('config.json'),read('registry.json'),read('assets.json'),read('audit.json'),loadWords()]);
const DRAFT_KEY='malaNauka.designStudio.v1';
let base=clone(initial),baseAssets=clone(initialAssets),config=clone(initial),assets=clone(initialAssets),page='components',viewId='spelling-settings',componentId='jelly',scope='global',inspecting=false,search='',assetFilter='all',assetPage=0,docSection='principles',busy=false;
let undo=[],redo=[],uploads=[],wordEdits=new Map(),objectURLs=new Map(),draftHistory=[],savedCommit=null;
const git=new GitClient();
const names={spelling:'Ortografia',english:'Angielski',flags:'Flagi',reading:'Czytanie',math:'Matematyka'};
const nav=[['components','▦','Komponenty'],['colors','◉','Kolory i odstępy'],['fonts','Aa','Typografia'],['assets','▧','Assety i słowa'],['views','⌘','Widoki i relacje'],['audit','≋','Porządek w kodzie'],['docs','▤','Dokumentacja'],['versions','↺','Wersje i szkice']];
const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const titleFor=id=>nav.find(row=>row[0]===id)?.[2]||'Design system';
const selectedView=()=>registry.views.find(view=>view.id===viewId)||registry.views[0];
const selectedComponent=()=>registry.components.find(component=>component.id===componentId)||registry.components[0];
const workspace=document.getElementById('workspace'),modal=document.getElementById('studio-modal');
const frame=()=>document.getElementById('device-frame');
const changes=()=>diff(base,config);
const assetChanges=()=>diff(baseAssets.words,assets.words);
try{const draft=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(draft?.schemaVersion===1&&draft.baseRevision===initial.revision&&draft.config){validateConfig(draft.config);config=draft.config;if(draft.assets)assets=draft.assets;draftHistory=draft.history||[];}}catch{}
function stash(){try{localStorage.setItem(DRAFT_KEY,JSON.stringify({schemaVersion:1,baseRevision:base.revision,config,assets,history:draftHistory.slice(-12)}));}catch{toast('Przeglądarka nie zapisała szkicu. Pobierz JSON przed zamknięciem.');}}
let toastTimer;
function toast(message){const element=document.getElementById('toast');element.textContent=message;element.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>element.classList.remove('visible'),4500);}
function checkpoint(){undo.push(clone(config));if(undo.length>50)undo.shift();redo=[];}
function header(){const count=changes().length+assetChanges().length+wordEdits.size;document.getElementById('page-title').textContent=titleFor(page);document.getElementById('draft-status').textContent=count?`${count} zmian w szkicu`:'Zapisana wersja';document.getElementById('change-count').textContent=count||'';document.getElementById('connect-git').textContent=git.connected?'GitHub połączony':'Połącz GitHub';document.getElementById('save-git').disabled=busy||!count;}
function sendDesign(){applyDesign(config);configureAssets(assets,new URL('../',import.meta.url).href);frame()?.contentWindow?.postMessage({channel:'mala-nauka-studio',type:'design',config,assets},location.origin);header();stash();}
function navigate(next){page=next;document.querySelectorAll('#navigation button').forEach(button=>button.classList.toggle('active',button.dataset.page===page));header();render();}
document.getElementById('navigation').innerHTML=nav.map(([id,icon,label])=>`<button type="button" data-page="${id}" class="${id===page?'active':''}" title="${label}"><span class="nav-icon" aria-hidden="true">${icon}</span><span class="nav-text">${label}</span></button>`).join('');
document.getElementById('navigation').addEventListener('click',event=>{const button=event.target.closest('[data-page]');if(button)navigate(button.dataset.page);});
const fieldLabels={canvasWidth:'Szerokość płótna',sidePadding:'Padding boków',safeTop:'Górna bezpieczna strefa',safeBottom:'Dolna bezpieczna strefa',sectionGap:'Odstęp sekcji',headerHeight:'Wysokość nagłówka',headerGap:'Odstęp w nagłówku',headerBottom:'Odstęp pod nagłówkiem',missionHeight:'Wysokość misji',missionBottom:'Odstęp pod misją',height:'Wysokość',radius:'Zaokrąglenie',paddingX:'Padding poziomy',paddingTop:'Padding górny',paddingBottom:'Padding dolny',padding:'Padding',borderWidth:'Grubość obrysu',inset:'Inset jelly',labelSize:'Rozmiar etykiety',labelWeight:'Waga etykiety',trackShadowY:'Przesunięcie cienia',trackShadowBlur:'Rozmycie cienia',trackShadowOpacity:'Krycie cienia',duration:'Czas animacji',inkDelay:'Opóźnienie koloru tekstu',inkDuration:'Animacja koloru tekstu',width:'Szerokość',widthPercent:'Szerokość grupy',fontSize:'Rozmiar tekstu',shadowY:'Przesunięcie podstawy',shadowBlur:'Rozmycie podstawy',gap:'Odstęp',handleSize:'Rozmiar uchwytu',threshold:'Próg zakończenia',maxHeightPercent:'Maksymalna wysokość',avatarSize:'Rozmiar avatara',size:'Rozmiar pucharu'};
function rangeFor(group,key){
 if(key==='canvasWidth')return[320,480,1,'px'];if(key==='duration')return[0,5000,50,'ms'];if(/Duration|Delay/.test(key))return[0,1500,10,'ms'];if(key==='labelWeight')return[400,950,50,''];if(key==='trackShadowOpacity')return[0,.5,.005,''];if(key==='threshold')return[70,100,1,'%'];if(key==='widthPercent'||key==='maxHeightPercent')return[50,100,1,'%'];if(key==='height'&&group==='jelly')return[28,96,1,'px'];if(key==='height')return[16,120,1,'px'];if(key==='width')return[60,220,1,'px'];if(/Size|size/.test(key))return[8,key==='avatarSize'||key==='size'?180:64,.2,'px'];if(/radius/.test(key))return[4,60,1,'px'];if(/Height/.test(key))return[20,150,1,'px'];if(/Opacity/.test(key))return[0,1,.01,''];return[0,60,.5,'px'];
}
function tokenPath(group,key){return scope==='view'?`overrides.${viewId}.${group}.${key}`:`tokens.${group}.${key}`;}
function effective(group,key){return(scope==='view'?get(config,`overrides.${viewId}.${group}.${key}`):undefined)??config.tokens[group][key];}
function control(group,key){const [min,max,step,unit]=rangeFor(group,key),value=effective(group,key);return `<div class="control"><div class="control-top"><label for="range-${group}-${key}">${fieldLabels[key]||key}</label><span class="control-value"><input aria-label="${fieldLabels[key]||key}" type="number" data-token="${group}.${key}" value="${value}" min="${min}" max="${max}" step="${step}"><span>${unit}</span></span></div><input id="range-${group}-${key}" aria-label="${fieldLabels[key]||key}" type="range" data-token="${group}.${key}" min="${min}" max="${max}" step="${step}" value="${value}"><div class="control-limits"><span>${min} ${unit}</span><span>${max} ${unit}</span></div></div>`;}
function viewURL(view=selectedView()){const url=new URL(view.route,location.origin);url.search=new URLSearchParams({studio:'1',mode:view.mode,screen:view.screen,state:view.state,viewId:view.id}).toString();return url.href;}
function phone(){return `<div class="phone-zone"><div class="phone-outer"><div class="phone-inner"><iframe id="device-frame" title="Rzeczywisty ekran Małej Nauki w symulatorze iPhone 13 Pro" src="${escape(viewURL())}"></iframe><div class="phone-notch"></div><div class="phone-status"><span>9:41</span><span class="phone-signals">▮▮▮ ◔ ▰</span></div><div class="phone-homebar"></div></div><span class="phone-note">390 × 844 pt · eksport testów: 1170 × 2532 px</span></div></div>`;}
function renderComponents(){
 const view=selectedView(),component=selectedComponent(),modeViews=registry.views.filter(row=>row.mode===view.mode||['players','players-empty','home','player-create','player-pin','settings','progress','collection','trophies','categories','rules','sessions'].includes(row.id));
 workspace.innerHTML=`<div class="component-layout"><section class="preview-column"><div class="preview-toolbar"><select id="mode-select" aria-label="Tryb gry">${Object.entries(names).map(([id,name])=>`<option value="${id}" ${id===view.mode?'selected':''}>${name}</option>`).join('')}</select><select id="view-select" aria-label="Widok i stan">${modeViews.map(row=>`<option value="${row.id}" ${row.id===viewId?'selected':''}>${escape(row.name)}</option>`).join('')}</select></div><div class="component-strip">${registry.components.map(row=>`<button type="button" data-component="${row.id}" class="${row.id===componentId?'selected':''}">${escape(row.name)}</button>`).join('')}</div><div class="preview-subbar"><label><input type="checkbox" id="inspect-mode" ${inspecting?'checked':''}>Wskaż komponent na ekranie</label><a href="${escape(viewURL())}" target="_blank" rel="noopener">Otwórz podgląd ↗</a></div>${phone()}</section><aside id="inspector" class="inspector"></aside></div>`;
 renderInspector();frame().addEventListener('load',()=>{sendDesign();sendInspect();});
}
function renderInspector(){
 const component=selectedComponent(),group=component.tokenGroup,used=registry.views.filter(view=>view.components.includes(component.id));
 document.getElementById('inspector').innerHTML=`<span class="inspector-kicker">${escape(group)} / komponent</span><h2>${escape(component.name)}</h2><p class="description">${escape(component.description)}</p><label class="scope"><span>Zakres zmiany</span><select id="scope-select"><option value="global" ${scope==='global'?'selected':''}>Wszędzie — wspólny komponent</option><option value="view" ${scope==='view'?'selected':''}>Tylko: ${escape(selectedView().name)}</option></select></label><div>${Object.keys(config.tokens[group]).filter(key=>typeof config.tokens[group][key]==='number').map(key=>control(group,key)).join('')}</div><div class="inspector-bottom"><button class="small-button" id="reset-component">Przywróć zapisane wartości</button><div class="affected"><strong>${used.length} widoków</strong> korzysta z komponentu<div class="affected-chips">${[...new Set(used.map(view=>names[view.mode]))].map(name=>`<span>${name}</span>`).join('')}</div></div><p class="description" id="component-metrics"></p></div>`;
}
function sendInspect(){frame()?.contentWindow?.postMessage({channel:'mala-nauka-studio',type:'inspect',enabled:inspecting},location.origin);}
function renderColors(){
 workspace.innerHTML=`<div class="content-page"><div class="page-intro"><div><h2>Jeden rytm. Pięć kolorów.</h2><p>Tryb zmienia paletę i ilustrację. Wymiary komponentów pozostają wspólne.</p></div><button class="quiet-button" data-open-components>Sprawdź na ekranie</button></div><div class="color-modes">${Object.entries(config.themes).map(([mode,theme])=>`<article class="theme-card"><div class="theme-hero" style="background:linear-gradient(160deg,${theme.light},${theme.accent})">${names[mode]}</div><div class="theme-fields">${[['accent','Główny'],['light','Światło'],['middle','Środek'],['bottom','Głębia'],['border','Obrys'],['lip','Podstawa'],['activeInk','Aktywny tekst'],['idleInk','Nieaktywny tekst']].map(([key,label])=>`<label class="color-field"><span>${label}</span><div><input type="color" aria-label="${names[mode]} ${label}" data-color="themes.${mode}.${key}" value="${theme[key].slice(0,7)}"><input type="text" aria-label="${names[mode]} ${label} HEX" data-color="themes.${mode}.${key}" value="${theme[key]}" maxlength="9"></div></label>`).join('')}</div></article>`).join('')}</div><section class="panel" style="margin-top:24px"><h3>Kolory wspólne</h3><div style="display:flex;gap:24px;flex-wrap:wrap">${Object.entries(config.tokens.color).map(([key,value])=>`<label class="color-field"><span>${key}</span><input type="color" data-color="tokens.color.${key}" value="${value}" aria-label="${key}"></label>`).join('')}</div></section><section class="panel"><h3>Skala odstępów</h3><p style="color:#8292ae;font-size:12px;margin-bottom:15px">Punkty odniesienia dla nowych układów. Konkretne odstępy istniejących komponentów edytujesz w zakładce Komponenty.</p><div style="display:flex;gap:20px;flex-wrap:wrap">${Object.entries(config.tokens.space).map(([key,value])=>`<label class="form-field"><span>${key.toUpperCase()}</span><input type="number" data-space="${key}" value="${value}" min="0" max="64" style="width:70px"></label>`).join('')}</div></section></div>`;
}
const roles={body:'Tekst i opisy',ui:'Kontrolki i etykiety',display:'Nagłówki i ortografia',flag:'Nazwy krajów'};
function renderFonts(){workspace.innerHTML=`<div class="content-page"><div class="page-intro"><div><h2>Cztery fonty. Jawne role.</h2><p>Osiem historycznych nazw sprowadzono do czterech plików. Zmiana lub scalenie przenosi wszystkie role korzystające z fontu.</p></div></div><div class="summary-strip"><div class="summary-card"><b>4</b><span>rzeczywiste rodziny</span></div><div class="summary-card"><b>4</b><span>pliki fontów</span></div><div class="summary-card"><b>8 → 4</b><span>nazwy w kodzie</span></div><div class="summary-card"><b>ĄĆĘŁŃÓŚŹŻ</b><span>polskie znaki</span></div></div><div class="font-grid">${FONT_IDS.map(id=>{const assigned=Object.entries(config.typography).filter(([,font])=>font===id).map(([role])=>roles[role]);return `<article class="font-card"><header><h3>${id==='dynapuff'?'DynaPuff':id==='nunito'?'Nunito':id==='dosis'?'Dosis':'Fredoka'}</h3><span class="tag">${id==='dynapuff'?'700':'variable'}</span></header><p class="font-meta">${FONT_FILES[id]} · ${FONT_NAMES[id]}</p><p class="font-sample" style="font-family:'${FONT_NAMES[id]}'">Małe kroki, wielkie odkrycia.<br>Zażółć gęślą jaźń.</p><div class="font-usage"><strong>Role:</strong> ${assigned.join(', ')||'Obecnie bez przypisanej roli'}<br><strong>Widoki:</strong> ${id==='fredoka'?'Gra flagi — nazwy krajów':id==='dynapuff'?'Nagłówki, gra i wyniki ortografii, profile':id==='dosis'?'Home, ustawienia czterech trybów, jelly, CTA':'Wszystkie widoki — opisy, etykiety i liczby'}</div><div class="font-actions"><select data-font-target="${id}" aria-label="Zamień ${id} na">${FONT_IDS.filter(other=>other!==id).map(other=>`<option value="${other}">${other}</option>`).join('')}</select><button class="small-button" data-merge-font="${id}">Scal / zamień</button></div></article>`;}).join('')}</div><section class="panel" style="margin-top:22px"><h3>Przypisanie do roli</h3><div style="display:flex;gap:22px;flex-wrap:wrap">${Object.entries(roles).map(([role,label])=>`<label class="form-field"><span>${label}</span><select data-font-role="${role}">${FONT_IDS.map(id=>`<option value="${id}" ${config.typography[role]===id?'selected':''}>${id}</option>`).join('')}</select></label>`).join('')}</div></section><section class="panel"><h3>Historia nazw</h3><div class="table-wrap"><table class="table"><thead><tr><th>Plik</th><th>Dawne nazwy</th><th>Wspólna nazwa</th></tr></thead><tbody><tr><td>Nunito</td><td>ResultBody · MN Soft · Flag Body</td><td>MN Body</td></tr><tr><td>DynaPuff</td><td>ResultDisplay · Spelling</td><td>MN Display</td></tr><tr><td>Dosis</td><td>Home Rounded</td><td>MN UI</td></tr><tr><td>Fredoka</td><td>Flag Display</td><td>MN Flag</td></tr></tbody></table></div></section></div>`;}
const wordPicture=word=>objectURLs.get(assets.words[word]?.path)|| (assets.words[word]?.path?assetUrl(assets.words[word].path):'');
function filteredWords(){return words.filter(word=>(!search||word.word.toLocaleLowerCase('pl').includes(search.toLocaleLowerCase('pl'))||word.category.includes(search))&&(assetFilter==='all'||assetFilter==='missing'&&!assets.words[word.word]||assetFilter==='ready'&&assets.words[word.word])).sort((a,b)=>a.word.localeCompare(b.word,'pl'));}
function wordCards(){const pool=filteredWords(),pages=Math.max(1,Math.ceil(pool.length/30));assetPage=Math.min(assetPage,pages-1);return `<div class="word-grid">${pool.slice(assetPage*30,assetPage*30+30).map(word=>{const picture=wordPicture(word.word);return `<article class="word-card">${picture?`<img src="${escape(picture)}" alt="${escape(word.word)}" loading="lazy" decoding="async" width="300" height="300">`:'<div class="missing-picture" aria-label="Brak ilustracji">＋</div>'}<strong>${escape(word.word)}</strong><small>${escape(word.category)} · poziom ${word.difficulty}</small><div class="word-actions"><button data-word-details="${escape(word.word)}">Dane</button><button data-upload-word="${escape(word.word)}">${picture?'Zmień grafikę':'Dodaj grafikę'}</button></div></article>`;}).join('')}</div><div class="pagination"><button class="small-button" data-asset-page="${assetPage-1}" ${assetPage===0?'disabled':''}>Poprzednia</button><span>${assetPage+1} / ${pages} · ${pool.length} słów</span><button class="small-button" data-asset-page="${assetPage+1}" ${assetPage===pages-1?'disabled':''}>Następna</button></div>`;}
function renderAssets(){workspace.innerHTML=`<div class="content-page"><div class="page-intro"><div><h2>Jedna baza ilustracji i słów</h2><p>Każde słowo ma jedno przypisanie do pliku. Identyczne ilustracje współdzielą asset; zmiana pojedynczego słowa zachowuje pozostałe przypisania.</p></div><button class="solid-button" id="upload-asset">Wgraj asset</button></div><div class="summary-strip"><div class="summary-card"><b>${words.length}</b><span>słów w bazie</span></div><div class="summary-card"><b>${Object.keys(assets.words).length}</b><span>słów z ilustracją</span></div><div class="summary-card"><b>${assets.assets.length}</b><span>unikalnych plików</span></div><div class="summary-card"><b>${Object.keys(assets.aliases).length}</b><span>scalonych kopii</span></div></div><div class="searchbar"><input id="asset-search" aria-label="Szukaj słowa" placeholder="Szukaj słowa lub kategorii…" value="${escape(search)}"><select id="asset-filter" aria-label="Ilustracje"><option value="all" ${assetFilter==='all'?'selected':''}>Wszystkie słowa</option><option value="ready" ${assetFilter==='ready'?'selected':''}>Z ilustracją</option><option value="missing" ${assetFilter==='missing'?'selected':''}>Bez ilustracji</option></select><button class="quiet-button" id="asset-inventory">Wszystkie assety</button></div><div id="word-cards">${wordCards()}</div></div>`;}
function renderViews(){workspace.innerHTML=`<div class="content-page"><div class="page-intro"><div><h2>Widoki, stany i warunki</h2><p>Każdy wpis otwiera prawdziwy renderer. Dane przykładowe oraz zatrzymany zegar pozwalają porównać stan przed odpowiedzią, po poprawnej i po błędnej odpowiedzi.</p></div></div><section class="panel"><h3>Przepływ gry</h3><div class="flow-list">${registry.flows.map(row=>`<div class="flow-row"><strong>${escape(row.from)}</strong><div><p>${escape(row.action)}</p><small>${escape(row.condition)}</small></div><div>${row.to.map(id=>`<span class="tag">${escape(id)}</span>`).join(' ')}</div></div>`).join('')}</div></section><section class="panel"><h3>${registry.views.length} widoków i stanów</h3><div class="table-wrap"><table class="table"><thead><tr><th>Widok</th><th>Stan</th><th>Komponenty</th><th>Odstępstwa</th><th></th></tr></thead><tbody>${registry.views.map(view=>`<tr><td><strong>${escape(view.name)}</strong><br><small>${escape(view.route)}</small></td><td><span class="tag">${view.state}</span></td><td>${view.components.join(' · ')}</td><td>${Object.keys(config.overrides[view.id]||{}).join(', ')||'Wspólne zasady'}</td><td><button class="small-button" data-open-view="${view.id}">Otwórz</button></td></tr>`).join('')}</tbody></table></div></section><section class="panel"><h3>Wspólne modele interakcji</h3><table class="table"><thead><tr><th>Rodzina</th><th>Tryby</th><th>Różnica</th></tr></thead><tbody><tr><td>Fiszka płaska</td><td>Angielski · Czytanie</td><td>Treść + odpowiedzi, bez warstwy mapy lub bańki</td></tr><tr><td>Fiszka wzbogacona</td><td>Ortografia · Flagi</td><td>Bańka + odsłanianie słowa / flaga + odsłanianie mapy</td></tr><tr><td>Tablica działań</td><td>Matematyka</td><td>Osobna mechanika objaśniania; wspólne role fontów i tokeny odpowiedzi</td></tr></tbody></table></section></div>`;}
function renderAudit(){workspace.innerHTML=`<div class="content-page"><div class="page-intro"><div><h2>Porządek bez utraty działających ekranów</h2><p>Raport pochodzi z analizy plików i odwołań. Historii zmian nie kopiujemy do aktywnego interfejsu — pozostaje w Git.</p></div></div><div class="summary-strip"><div class="summary-card"><b>${audit.cleanup?.removedAssets||28}</b><span>usuniętych identycznych kopii</span></div><div class="summary-card"><b>${((audit.cleanup?.savedAssetBytes||7473392)/1000000).toFixed(1)} MB</b><span>mniej ilustracji</span></div><div class="summary-card"><b>${audit.cleanup?.removedCodeFiles||0}</b><span>nieaktywnych plików usuniętych</span></div><div class="summary-card"><b>8 → 4</b><span>uporządkowane nazwy fontów</span></div></div><section class="panel"><h3>Granice warstw</h3><table class="table"><thead><tr><th>Warstwa</th><th>Odpowiedzialność</th><th>Źródło</th></tr></thead><tbody><tr><td>Tokeny</td><td>Wymiary, paleta, odstępy, role fontów</td><td>design-system/config.json</td></tr><tr><td>Komponenty</td><td>Wspólna geometria oraz stany</td><td>shared/components.css + jelly-v4.mjs</td></tr><tr><td>Widoki</td><td>Kompozycja, treść i ilustracja konkretnego trybu</td><td>registry.json + renderery trybów</td></tr><tr><td>Assety</td><td>Unikalny plik, hash, przypisania i miniatura słowa</td><td>design-system/assets.json</td></tr><tr><td>Build</td><td>Łączenie CSS, wspólne źródło, kontrola odwołań</td><td>tools/build-design.mjs</td></tr></tbody></table></section><section class="panel"><h3>Pliki wymagające uwagi</h3><div class="table-wrap"><table class="table"><thead><tr><th>Plik</th><th>Rozmiar</th><th>Uwagi</th></tr></thead><tbody>${(audit.largeFiles||[]).slice(0,14).map(row=>`<tr><td>${escape(row.path)}</td><td>${(row.bytes/1024).toFixed(1)} kB</td><td>${escape(row.note||'Aktywny renderer / styl. Dalsze wydzielanie po pomiarze regresji.')}</td></tr>`).join('')}</tbody></table></div></section><section class="panel"><h3>Reguły dalszego porządkowania</h3><p style="font-size:13px;color:#7486a5">Nowy kolor trafia do palety. Nowy wymiar trafia do tokenów. Wyjątek widoku trafia do rejestru odstępstw. Usuwamy plik dopiero po sprawdzeniu wszystkich aktywnych odwołań i offline-cache. Budowanie łączy warstwy CSS w pojedynczy arkusz na stronę.</p></section></div>`;}
const docs={
 principles:['Zasady systemu',`<p>Ortografia wyznacza kształt jelly, układ ustawień i język wizualny. Cień pod całym kontrolerem przyjmujemy z angielskiego. Tryb dostarcza kolor i scenę; komponent dostarcza wymiary i zachowanie.</p><p>Docelowe płótno ma <strong>390 × 844 pt</strong>, bezpieczne strefy 47 / 34 pt, a testowy zrzut Retina <strong>1170 × 2532 px</strong>. Skala desktopowego telefonu zmienia tylko powiększenie podglądu. Układ wewnątrz pozostaje 390 × 844.</p><p>Nie przemalowujemy ani nie rozciągamy logo. Ilustracje scen mają własną warstwę i nie sterują wymiarami kontrolek.</p>`],
 editing:['Jak edytować',`<ol><li>Wybierz tryb oraz widok i stan.</li><li>Wybierz komponent z listy lub włącz „Wskaż komponent na ekranie”.</li><li>Zmieniaj suwaki lub dokładne wartości liczbowe. Podgląd korzysta z prawdziwego CSS i JS aplikacji.</li><li>Ustal zakres: wspólny komponent albo jawny wyjątek wybranego widoku.</li><li>Sprawdź powiązane widoki i zapisz commit.</li></ol><p>Szkic zapisuje się lokalnie. Cofanie i ponawianie obejmuje tokeny. Pliki wgrane przed commitem pozostają w pamięci bieżącej karty; komunikat przypomina o konieczności zapisu.</p>`],
 git:['Zapis i wersjonowanie',`<p>Panel zapisuje wyłącznie na <code>design/system-v1</code>. Połącz go z GitHub za pomocą fine-grained tokenu ograniczonego do <code>marcinhubicki-coder/mala-nauka</code> z uprawnieniem <strong>Contents: Read and write</strong>. Token pozostaje w pamięci karty; nie zapisujemy go do localStorage, plików ani commitów.</p><p>Zapis tworzy jeden commit obejmujący tokeny, przypisania assetów, wgrane pliki i zmienione słowa. GitHub wymusza fast-forward. Równoległy commit zatrzymuje zapis i pozwala scalić szkic, zachowując Twoje zmiany.</p><p>Vercel tworzy preview tego brancha. Produkcja korzysta z main; publikacja zmian do main jest osobną decyzją.</p>`],
 assets:['Jedno źródło assetów',`<p>Własne grafiki i osiem paczek słów mają źródło w branchu design systemu. Konsument podczas builda pobiera wspólny kontrakt, a jego CSS i HTML używają centralnych URL-i. Konsument nie publikuje swojej kopii katalogu assets.</p><p>Klucz słowa wskazuje jeden plik. Identyczne pliki wykrywa SHA-256; połączenie nie zależy od nazwy. Nowy upload otrzymuje adres z hashem, więc poprzednia ilustracja pozostaje dostępna w historii Git.</p><p>Przypisanie grafiki do jednego słowa nie zmienia ilustracji innych słów, nawet gdy wcześniej używały identycznego pliku. Caching offline jest oddzielny od kopii źródłowych — gra zachowuje pobrane zasoby na urządzeniu.</p>`],
 structure:['Struktura i integracja',`<pre class="code-block">design-system/config.json     tokeny i wyjątki\ndesign-system/registry.json   widoki, komponenty, warunki\ndesign-system/assets.json     pliki i przypisania słów\nshared/components.css          wspólna geometria\nshared/design-runtime.mjs      zastosowanie kontraktu\nshared/asset-loader.mjs        baza i rozwiązywanie URL-i\ntools/build-design.mjs         build i wspólne źródło\ndocs/design-system/            pełna dokumentacja</pre><p>Nowe branche startują z tego brancha lub korzystają z integratora. Nie kopiuj katalogów ilustracji z historycznych branchów. Zachowaj istniejącą mechanikę gry, a nowy widok dodaj do registry.json.</p>`],
 interactions:['Stany i zachowania',`<p>Jelly obsługuje kliknięcie, przeciąganie i klawiaturę. Tekst staje się biały po opóźnieniu dopasowanym do ruchu. Tryb reduced-motion ogranicza animacje.</p><p>Odpowiedź ma stan początkowy, poprawny, błędny i wyłączony. Po błędzie czas zatrzymuje się. Ortografia przechodzi dalej sliderem z progiem ukończenia; działa również z klawiatury.</p><p>Podgląd używa danych przykładowych i zatrzymanego zegara. Nie zapisuje wyników dzieci ani nie zmienia ich profili. Symulator nie zastępuje końcowego testu Safari/PWA na prawdziwym iPhonie.</p>`]
};
function renderDocs(){const [title,content]=docs[docSection];workspace.innerHTML=`<div class="content-page"><div class="page-intro"><div><h2>Dokumentacja Małej Nauki</h2><p>Zasady dla edycji, przyszłych ekranów i generowania mockupów.</p></div><a class="quiet-button" href="https://github.com/${REPOSITORY}/tree/${BRANCH}/docs/design-system" target="_blank" rel="noopener">Pełna dokumentacja na GitHub ↗</a></div><div class="docs-layout"><nav class="docs-nav" aria-label="Dokumentacja">${Object.entries(docs).map(([id,[label]])=>`<a href="#${id}" data-doc="${id}">${label}</a>`).join('')}</nav><article class="panel doc-body"><h2>${title}</h2>${content}</article></div></div>`;}
function renderVersions(){workspace.innerHTML=`<div class="content-page"><div class="page-intro"><div><h2>Twoja wersja i szkic</h2><p>Zapisany kontrakt: rewizja ${base.revision}. Szkic: ${changes().length} zmian tokenów i ${assetChanges().length} zmian przypisań.</p></div><button class="quiet-button" id="refresh-git">Wczytaj i scal z GitHub</button></div><section class="panel"><h3>Zmiany w szkicu</h3><div class="change-list">${changes().length?`<ul>${changes().map(row=>`<li><b>${escape(row.path)}</b><br>${escape(JSON.stringify(row.before))} → ${escape(JSON.stringify(row.after))}</li>`).join('')}</ul>`:'<p style="color:#8392ab">Brak niezapisanych zmian tokenów.</p>'}</div><div class="modal-actions"><button class="quiet-button" id="undo-change" ${undo.length?'':'disabled'}>Cofnij</button><button class="quiet-button" id="redo-change" ${redo.length?'':'disabled'}>Ponów</button><button class="quiet-button" id="export-design">Pobierz JSON</button><button class="quiet-button" id="import-design">Importuj JSON</button></div></section><section class="panel"><h3>Zapisane szkice tej przeglądarki</h3><div class="version-list">${draftHistory.length?draftHistory.map((row,index)=>`<div class="version-row"><strong>${escape(row.label)}</strong><small>${new Date(row.date).toLocaleString('pl-PL')}</small><button class="small-button" data-restore-draft="${index}">Przywróć</button></div>`).join(''):'<p style="color:#8392ab;font-size:12px">Historia pojawi się po zapisaniu commitu.</p>'}</div></section><section class="panel"><h3>Historia Git</h3><a class="small-button" href="https://github.com/${REPOSITORY}/commits/${BRANCH}" target="_blank" rel="noopener">Otwórz commity ↗</a>${savedCommit?`<p style="margin-top:15px;font-size:12px"><a href="${savedCommit.url}" target="_blank" rel="noopener">Ostatni commit: ${savedCommit.sha.slice(0,7)}</a></p>`:''}</section></div>`;}
function render(){({components:renderComponents,colors:renderColors,fonts:renderFonts,assets:renderAssets,views:renderViews,audit:renderAudit,docs:renderDocs,versions:renderVersions}[page]||renderComponents)();}
workspace.addEventListener('change',event=>{
 const target=event.target;
 if(target.id==='mode-select'){viewId=target.value+'-settings';renderComponents();}
 if(target.id==='view-select'){viewId=target.value;renderComponents();}
 if(target.id==='scope-select'){scope=target.value;renderInspector();}
 if(target.id==='inspect-mode'){inspecting=target.checked;sendInspect();}
 if(target.id==='asset-filter'){assetFilter=target.value;assetPage=0;document.getElementById('word-cards').innerHTML=wordCards();}
 if(target.dataset.fontRole){checkpoint();config.typography[target.dataset.fontRole]=target.value;sendDesign();renderFonts();}
 if(target.dataset.space){checkpoint();config.tokens.space[target.dataset.space]=Math.max(0,Math.min(64,Number(target.value)));sendDesign();}
 if(target.dataset.token)header();
});
let lastToken='';
workspace.addEventListener('input',event=>{
 const target=event.target;
 if(target.dataset.token){
  const [group,key]=target.dataset.token.split('.'),[min,max]=rangeFor(group,key),value=Number(target.value);if(!Number.isFinite(value)||value<min||value>max)return;
  if(lastToken!==target.dataset.token){checkpoint();lastToken=target.dataset.token;}
  set(config,tokenPath(group,key),value);
  for(const other of workspace.querySelectorAll(`[data-token="${target.dataset.token}"]`))if(other!==target)other.value=value;
  sendDesign();
 }
 if(target.dataset.color&&/^#[0-9a-f]{6}([0-9a-f]{2})?$/i.test(target.value)){if(lastToken!==target.dataset.color){checkpoint();lastToken=target.dataset.color;}set(config,target.dataset.color,target.value);sendDesign();for(const other of workspace.querySelectorAll(`[data-color="${target.dataset.color}"]`))if(other!==target)other.value=target.value;}
 if(target.id==='asset-search'){search=target.value;assetPage=0;document.getElementById('word-cards').innerHTML=wordCards();}
});
workspace.addEventListener('pointerup',()=>{lastToken='';});
workspace.addEventListener('click',async event=>{
 const button=event.target.closest('button,a');if(!button)return;
 if(button.dataset.component){componentId=button.dataset.component;workspace.querySelectorAll('[data-component]').forEach(node=>node.classList.toggle('selected',node.dataset.component===componentId));renderInspector();}
 if(button.dataset.openView){viewId=button.dataset.openView;navigate('components');}
 if(button.dataset.openComponents!==undefined)navigate('components');
 if(button.id==='reset-component'){checkpoint();const group=selectedComponent().tokenGroup;if(scope==='view')delete config.overrides[viewId]?.[group];else config.tokens[group]=clone(base.tokens[group]);sendDesign();renderInspector();}
 if(button.dataset.mergeFont){const from=button.dataset.mergeFont,to=workspace.querySelector(`[data-font-target="${from}"]`).value;checkpoint();for(const role of Object.keys(config.typography))if(config.typography[role]===from)config.typography[role]=to;sendDesign();renderFonts();toast(`Role ${from} korzystają teraz z ${to}. Zapisz commit po sprawdzeniu widoków.`);}
 if(button.dataset.assetPage!==undefined){assetPage=Number(button.dataset.assetPage);document.getElementById('word-cards').innerHTML=wordCards();}
 if(button.id==='upload-asset'||button.dataset.uploadWord)openUpload(button.dataset.uploadWord||'');
 if(button.dataset.wordDetails)openWord(button.dataset.wordDetails);
 if(button.id==='asset-inventory')openInventory();
 if(button.dataset.doc){event.preventDefault();docSection=button.dataset.doc;renderDocs();}
 if(button.id==='undo-change'&&undo.length){redo.push(clone(config));config=undo.pop();sendDesign();render();}
 if(button.id==='redo-change'&&redo.length){undo.push(clone(config));config=redo.pop();sendDesign();render();}
 if(button.id==='export-design')downloadJSON(config,'mala-nauka-design-system.json');
 if(button.id==='import-design'){const input=Object.assign(document.createElement('input'),{type:'file',accept:'.json,application/json'});input.onchange=async()=>{try{const value=validateConfig(JSON.parse(await input.files[0].text()));checkpoint();config=value;sendDesign();render();toast('Kontrakt wczytany do szkicu.');}catch(error){toast(error.message);}};input.click();}
 if(button.id==='refresh-git')await refreshGit();
 if(button.dataset.restoreDraft!==undefined){checkpoint();config=clone(draftHistory[Number(button.dataset.restoreDraft)].config);sendDesign();render();}
});
function downloadJSON(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const link=Object.assign(document.createElement('a'),{href:url,download:name});link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
window.addEventListener('message',event=>{
 if(event.origin!==location.origin||event.source!==frame()?.contentWindow||event.data?.channel!=='mala-nauka-studio')return;
 if(event.data.type==='ready'){sendDesign();sendInspect();}
 if(event.data.type==='select'){componentId=event.data.component;renderInspector();workspace.querySelectorAll('[data-component]').forEach(node=>node.classList.toggle('selected',node.dataset.component===componentId));const metrics=event.data.metrics;document.getElementById('component-metrics').textContent=`Zmierzony element: ${metrics.width.toFixed(1)} × ${metrics.height.toFixed(1)} px · padding ${metrics.padding} · font ${metrics.fontSize}.`;}
});
function showDialog(html){modal.innerHTML=html;modal.showModal();modal.querySelector('[data-close]')?.addEventListener('click',()=>modal.close());}
function openConnect(){
 showDialog(`<h2>Połącz GitHub</h2><p>Zapis trafia na <strong>${BRANCH}</strong> w repozytorium Małej Nauki.</p><p>Użyj fine-grained tokenu z dostępem do tego repozytorium i uprawnieniem <strong>Contents: Read and write</strong>. Token pozostaje w pamięci tej karty.</p><a class="small-button" href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noopener">Utwórz token na GitHub ↗</a><form id="git-form"><label class="form-field"><span>Token GitHub</span><input id="git-token" type="password" autocomplete="off" spellcheck="false" required placeholder="github_pat_…"></label><p id="git-error" class="modal-error" role="alert"></p><div class="modal-actions"><button type="button" data-close class="quiet-button">Anuluj</button><button type="submit" class="solid-button">Połącz</button></div></form>`);
 modal.querySelector('form').onsubmit=async event=>{event.preventDefault();const input=modal.querySelector('#git-token'),token=input.value;input.value='';const submit=modal.querySelector('[type=submit]');submit.disabled=true;try{const connection=await git.connect(token,base);if(connection.stale){const latest=await git.latest();config=mergeDraft(base,config,latest.config);base=clone(latest.config);baseAssets=clone(latest.assets);assets=clone(latest.assets);git.acceptHead(latest.head);}modal.close();sendDesign();render();toast('GitHub połączony. Możesz zapisać commit.');}catch(error){modal.querySelector('#git-error').textContent=error.message;submit.disabled=false;}};
}
document.getElementById('connect-git').onclick=()=>{if(git.connected){showDialog('<h2>GitHub połączony</h2><p>Token jest dostępny tylko w tej karcie.</p><div class="modal-actions"><button class="quiet-button" data-close>Zamknij</button><button class="solid-button" id="disconnect-git">Rozłącz</button></div>');modal.querySelector('#disconnect-git').onclick=()=>{git.disconnect();header();modal.close();};}else openConnect();};
async function refreshGit(){if(!git.connected){openConnect();return;}try{const latest=await git.latest();config=mergeDraft(base,config,latest.config);const mergedWords=mergeDraft(baseAssets.words,assets.words,latest.assets.words);base=clone(latest.config);baseAssets=clone(latest.assets);assets=clone(latest.assets);assets.words=mergedWords;git.acceptHead(latest.head);sendDesign();render();toast('Wczytano GitHub i zachowano Twój szkic.');}catch(error){toast(error.message+(error.paths?.length?' '+error.paths.join(', '):''));}}
document.getElementById('save-git').onclick=()=>{
 if(!git.connected){openConnect();return;}
 const changed=changes(),affected=changedViews(changed,registry);
 showDialog(`<h2>Zapisz zmianę systemu</h2><p><strong>${changed.length}</strong> zmian tokenów · <strong>${assetChanges().length}</strong> przypisań · <strong>${uploads.length}</strong> plików · <strong>${affected.length}</strong> powiązanych widoków.</p><div class="change-list"><ul>${changed.slice(0,30).map(row=>`<li><b>${escape(row.path)}</b>: ${escape(JSON.stringify(row.before))} → ${escape(JSON.stringify(row.after))}</li>`).join('')}</ul></div><label class="form-field"><span>Opis commitu</span><input id="commit-message" value="Design system: aktualizacja komponentów" maxlength="160"></label><p id="save-error" class="modal-error" role="alert"></p><div class="modal-actions"><button class="quiet-button" data-close>Anuluj</button><button class="solid-button" id="confirm-save">Zapisz commit</button></div>`);
 modal.querySelector('#confirm-save').onclick=async()=>{
  busy=true;header();modal.querySelector('#confirm-save').disabled=true;
  const next=clone(config);next.revision=Number(base.revision)+1;const catalog=clone(assets);catalog.revision=Number(baseAssets.revision)+1;
  try{savedCommit=await git.save({config:next,assets:catalog,uploads,wordEdits:[...wordEdits.values()],message:modal.querySelector('#commit-message').value.trim()||'Design system: aktualizacja'});draftHistory.unshift({date:new Date().toISOString(),label:`Rewizja ${base.revision}`,config:clone(base)});config=next;assets=catalog;base=clone(next);baseAssets=clone(catalog);uploads=[];wordEdits.clear();undo=[];redo=[];stash();modal.close();toast(`Commit ${savedCommit.sha.slice(0,7)} zapisany. Vercel przygotuje nowy preview.`);render();}
  catch(error){modal.querySelector('#save-error').textContent=error.message;modal.querySelector('#confirm-save').disabled=false;}
  finally{busy=false;header();}
 };
};
async function fileRecord(file){
 if(!file||file.size>12*1024*1024)throw Error('Wybierz grafikę do 12 MB.');
 if(!['image/png','image/jpeg','image/webp','image/avif'].includes(file.type))throw Error('Obsługujemy PNG, JPG, WebP i AVIF.');
 const bytes=new Uint8Array(await file.arrayBuffer()),digest=await crypto.subtle.digest('SHA-256',bytes),sha=[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join(''),extension={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/avif':'avif'}[file.type];
 const bitmap=await createImageBitmap(file),width=bitmap.width,height=bitmap.height;bitmap.close();
 return {path:`assets/managed/${sha}.${extension}`,sha,id:sha.slice(0,16),size:bytes.length,width,height,type:extension,group:'managed',references:[],bytes,file};
}
function openUpload(word=''){
 showDialog(`<h2>${word?`Ilustracja: ${escape(word)}`:'Wgraj asset'}</h2><p>Nowy plik dostaje adres z hashem. Przypisanie słowa aktualizuje wspólną bazę ilustracji.</p><form id="upload-form"><label class="form-field"><span>Grafika PNG / JPG / WebP / AVIF</span><input id="asset-file" type="file" accept="image/png,image/jpeg,image/webp,image/avif" required></label><label class="form-field"><span>Przypisz do słowa (opcjonalnie)</span><input id="upload-word" list="word-options" value="${escape(word)}"><datalist id="word-options">${words.map(row=>`<option value="${escape(row.word)}">`).join('')}</datalist></label><div id="upload-preview"></div><p id="upload-error" class="modal-error" role="alert"></p><div class="modal-actions"><button type="button" data-close class="quiet-button">Anuluj</button><button type="submit" class="solid-button">Dodaj do szkicu</button></div></form>`);
 let staged;
 modal.querySelector('#asset-file').onchange=async event=>{try{staged=await fileRecord(event.target.files[0]);const url=URL.createObjectURL(staged.file);modal.querySelector('#upload-preview').innerHTML=`<img class="modal-preview" src="${url}" alt="Podgląd wgrywanej ilustracji"><p>${staged.width} × ${staged.height} px · ${(staged.size/1024).toFixed(0)} kB</p>`;modal.querySelector('#upload-error').textContent='';}catch(error){staged=null;modal.querySelector('#upload-error').textContent=error.message;}};
 modal.querySelector('form').onsubmit=event=>{event.preventDefault();try{if(!staged)throw Error('Najpierw wybierz grafikę.');const label=modal.querySelector('#upload-word').value.trim();if(label&&!words.some(row=>row.word===label))throw Error('Wybierz istniejące słowo z listy.');if(label&&Math.abs(staged.width/staged.height-1)>.04)throw Error('Ilustracja słowa powinna mieć proporcję 1:1.');const existing=assets.assets.find(asset=>asset.sha===staged.sha),path=existing?.path||staged.path;if(!existing){const {bytes,file,...metadata}=staged;assets.assets.push(metadata);uploads.push({path,bytes});objectURLs.set(path,URL.createObjectURL(file));}if(label){const previous=assets.words[label],record=words.find(row=>row.word===label);assets.words[label]={path,source:previous?.source||sourceFor(record),masked:record.masked,manual:true};}sendDesign();modal.close();renderAssets();toast('Asset dodany do szkicu. Zapisz commit przed zamknięciem karty.');}catch(error){modal.querySelector('#upload-error').textContent=error.message;}};
}
function sourceFor(word){return audit.wordSources?.[word.word]||'data/words-01.json';}
function openWord(label){const word=words.find(row=>row.word===label);if(!word)return;showDialog(`<h2>${escape(word.word)}</h2>${wordPicture(label)?`<img class="modal-preview" src="${escape(wordPicture(label))}" alt="${escape(label)}">`:''}<p>${escape(word.masked)} · ${escape(word.category)} · poziom ${word.difficulty}</p><form id="word-form"><label class="form-field"><span>Tytuł zasady</span><input id="learning-title" value="${escape(word.learning?.title||'')}"></label><label class="form-field"><span>Wyjaśnienie</span><textarea id="learning-explanation">${escape(word.learning?.explanation||'')}</textarea></label><p>Plik: ${escape(sourceFor(word))}<br>Asset: ${escape(assets.words[label]?.path||'brak')}</p><p id="word-error" class="modal-error"></p><div class="modal-actions"><button type="button" class="quiet-button" data-close>Zamknij</button><button type="submit" class="solid-button">Zapisz do szkicu</button></div></form>`);modal.querySelector('form').onsubmit=async event=>{event.preventDefault();const path=sourceFor(word);try{let edit=wordEdits.get(path);if(!edit){const response=await fetch(new URL('../'+path,import.meta.url));edit={path,value:await response.json()};}const record=edit.value.find(row=>row.word===label);record.learning||={type:'memory',examples:[],relatedWords:[],forms:[],sources:[]};record.learning.title=modal.querySelector('#learning-title').value.trim();record.learning.explanation=modal.querySelector('#learning-explanation').value.trim();if(!record.learning.title||!record.learning.explanation)throw Error('Uzupełnij tytuł i wyjaśnienie.');word.learning=clone(record.learning);wordEdits.set(path,edit);header();modal.close();toast('Wyjaśnienie zmienione w szkicu. Zapisz commit.');}catch(error){modal.querySelector('#word-error').textContent=error.message;}};}
function openInventory(){showDialog(`<h2>Rejestr assetów</h2><p>${assets.assets.length} unikalnych plików. Hash i odwołania pozwalają sprawdzić użycie przed usunięciem.</p><div class="change-list" style="max-height:52vh"><table class="table"><thead><tr><th>Plik</th><th>Rozmiar</th><th>Odwołania</th></tr></thead><tbody>${assets.assets.map(asset=>`<tr><td>${escape(asset.path)}</td><td>${(asset.size/1024).toFixed(1)} kB</td><td>${asset.references?.length||0}</td></tr>`).join('')}</tbody></table></div><div class="modal-actions"><button class="quiet-button" data-close>Zamknij</button><button class="solid-button" id="export-assets">Pobierz rejestr JSON</button></div>`);modal.querySelector('#export-assets').onclick=()=>downloadJSON(assets,'mala-nauka-assets.json');}
window.addEventListener('beforeunload',event=>{if(uploads.length||wordEdits.size){event.preventDefault();event.returnValue='';}});
sendDesign();render();
