import {SURFACE_EFFECTS,SURFACE_FIELDS,DEFAULT_SURFACE,surfaceConfig} from '../shared/surface-effects.mjs';
import {jellyChoices,mountJellies} from './studio-jelly.mjs';
import {html} from './preview-model.mjs';
export class StudioGlobal{
 constructor(options){Object.assign(this,options);this.view='home';this.mode='all';this.panel=true;this.workspace.addEventListener('input',e=>this.input(e));this.workspace.addEventListener('change',e=>this.change(e));this.workspace.addEventListener('click',e=>this.click(e));window.addEventListener('message',e=>this.receive(e));}
 get isOpen(){return Boolean(this.workspace.querySelector('.global-lab'));}
 get value(){return surfaceConfig(this.getDesign().config.screenEffects?.[this.view]);}
 frame(){return this.workspace.querySelector('#global-frame');}
 render(){const v=this.registry.views.find(v=>v.id===this.view)||this.registry.views[0],url=new URL(v.route,location.origin);url.search=new URLSearchParams({studio:'1',mode:v.mode,screen:v.screen,state:v.state,viewId:v.id});const views=this.registry.views.filter(v=>this.mode==='all'||v.mode===this.mode);this.workspace.innerHTML=this.sectionNav()+`<section class="logo-lab global-lab" data-mobile-editor=motion><div class=logo-preview><div class="logo-toolbar global-toolbar">${jellyChoices('global-mode','Tryb',[['all','Wszystkie'],['spelling','Ortografia'],['english','Angielski'],['flags','Flagi'],['reading','Czytanie'],['math','Matematyka']],this.mode)}<label class=form-field><span>Ekran i stan</span><select id=global-view>${views.map(v=>`<option value=${v.id} ${this.view===v.id?'selected':''}>${html(v.name)}</option>`).join('')}</select></label><button class=small-button id=global-panel title="Schowaj / pokaż panel">⚙</button></div><div class=logo-stage><div class=logo-phone><iframe id=global-frame title="Efekt całego wybranego ekranu" src="${html(url.href)}" width=390 height=844></iframe></div></div></div><aside class="inspector logo-inspector"><header><span class=eyebrow>Animacje globalne</span><h2>Efekt ekranu</h2><p class=description>${html(v.name)}</p></header><div data-inspector-group=surface>${jellyChoices('global-effect','Warstwa na wierzchu',Object.entries(SURFACE_EFFECTS),this.value.effect)}<label class=form-field><span>Uruchamiaj</span><select id=global-trigger>${[['continuous','Stale'],['tap','Po dotknięciu ekranu'],['answer','Po odpowiedzi']].map(([id,label])=>`<option value=${id} ${this.value.effectTrigger===id?'selected':''}>${label}</option>`).join('')}</select></label><details class=motion-control-group open><summary>Wygląd i ruch</summary><div class=motion-control-body>${Object.entries(SURFACE_FIELDS).map(([key,[min,max,step,label]])=>`<div class=control><div class=control-top><label>${label}</label><input type=number data-global-field=${key} value=${this.value[key]} min=${min} max=${max} step=${step} aria-label="${label}"></div><input type=range data-global-field=${key} value=${this.value[key]} min=${min} max=${max} step=${step} aria-label="${label}"></div>`).join('')}<label class=form-field><span>Kolor</span><input type=color id=global-color value=${this.value.effectColor}></label></div></details><button class=small-button id=global-remove>Usuń efekt z tego ekranu</button></div></aside></section>`;mountJellies(this.workspace.querySelector('.logo-toolbar'));this.resize?.disconnect();this.resize=new ResizeObserver(()=>this.fit());this.resize.observe(this.workspace.querySelector('.logo-stage'));this.fit();}
 fit(){const stage=this.workspace.querySelector('.logo-stage');if(stage)stage.style.setProperty('--logo-scale',Math.max(.15,Math.min(1,(stage.clientHeight-24)/844,(stage.clientWidth-24)/390)));}
 write(key,value){this.edit(`screenEffects.${this.view}`,{...this.value,[key]:value});}
 sendDesign(){if(this.isOpen)this.frame()?.contentWindow?.postMessage({channel:'mala-nauka-studio',type:'design',...this.getDesign()},location.origin);}
 receive(e){if(!this.isOpen||e.origin!==location.origin||e.source!==this.frame()?.contentWindow||e.data?.channel!=='mala-nauka-studio'||e.data.type!=='ready')return;this.sendDesign();this.frame().contentWindow.postMessage({channel:'mala-nauka-studio',type:'inspect',enabled:false,highlight:false},location.origin);}
 input(e){if(!this.isOpen)return;const n=e.target;if(n.dataset.globalField){const key=n.dataset.globalField,[min,max]=SURFACE_FIELDS[key],value=Math.max(min,Math.min(max,Number(n.value)));if(!Number.isFinite(value))return;this.write(key,value);for(const input of this.workspace.querySelectorAll(`[data-global-field=${key}]`))if(input!==n)input.value=value;}if(n.id==='global-color')this.write('effectColor',n.value);}
 change(e){if(!this.isOpen)return;const n=e.target;if(n.dataset.studioNav==='global-mode'){this.mode=n.value;this.view=this.registry.views.find(v=>this.mode==='all'||v.mode===this.mode)?.id||'home';this.render();}if(n.dataset.studioNav==='global-effect')this.write('effect',n.value);if(n.id==='global-view'){this.view=n.value;this.render();}if(n.id==='global-trigger')this.write('effectTrigger',n.value);this.endEdit();}
 click(e){if(!this.isOpen)return;const b=e.target.closest('button');if(!b)return;if(b.id==='global-remove'){this.write('effect','none');this.endEdit();this.render();}if(b.id==='global-panel'){this.panel=!this.panel;this.workspace.querySelector('.global-lab').classList.toggle('panel-hidden',!this.panel);}}
 leave(){this.resize?.disconnect();}
}
