import {html} from './preview-model.mjs';
import {batchSummary,batchWords,candidateProblems,addCandidates,requeueRejected} from './batch-model.mjs';
import {wordSlots} from '../spelling/word-pools.mjs';

export class StudioBatches{
 constructor(options){Object.assign(this,options);this.id='';this.search='';this.filter='all';this.workspace.addEventListener('click',e=>this.click(e));this.workspace.addEventListener('change',e=>this.change(e));this.workspace.addEventListener('input',e=>{if(e.target.id==='batch-search'){this.search=e.target.value;this.renderRows();}});}
 get data(){return this.getData();}
 get batch(){const all=this.data.batches.batches;return all.find(b=>b.id===this.id&&b.stage!=='published')||all.find(b=>b.stage!=='published');}
 image(path){return path?this.picture(path):'';}
 render(){
  const {batches,words}=this.data,batch=this.batch,active=batches.batches.filter(b=>b.stage!=='published'),published=batches.batches.filter(b=>b.stage==='published');this.id=batch?.id||'';
  const counts=batchSummary(batches,this.data.activeWords||words);
  const history=published.length?`<details class="panel batch-history"><summary>Zakończone · ${published.length}</summary><p class=description>Zaakceptowane batche są tylko do podglądu i nie zajmują miejsca w kolejce roboczej.</p><div class=version-list>${published.map(b=>`<div class=version-row><strong>${html(b.name)}</strong><small>${b.words.filter(r=>r.selected).length} zaakceptowanych · ${b.words.filter(r=>!r.selected).length} odłożonych</small><button class=small-button data-history-batch="${b.id}">Podgląd</button></div>`).join('')}</div></details>`:'';
  this.workspace.innerHTML=`<div class="content-page batch-workspace" data-batch-review><div class=page-intro><div><h2>Nowe słowa · akceptacja grupami</h2><p>1. Zatwierdź listę → 2. dodaj ilustracje → 3. sprawdź i zaakceptuj cały batch.</p></div><button class=solid-button id=new-word-batch>Dodaj batch</button></div><div class=batch-pools>${counts.map(r=>`<div class="batch-pool ${r.remaining?'needs-more':'covered'}"><strong>${r.category}</strong><span>${r.active}/100 w grze</span><small>+${r.proposed} zaznaczonych · razem ${r.total}</small><b>${r.remaining?'Brakuje '+r.remaining:'Plan osiąga minimum'}</b></div>`).join('')}</div><p class=description>Plan uwzględnia zaznaczone propozycje. Dostępne w grze są hasła opublikowane po akceptacji i uzupełnieniu ilustracji. Kategorie powstają z pisowni automatycznie.</p>${history}${batch?`<div class=batch-toolbar><label class=form-field><span>Wybierz aktywny batch</span><select id=batch-select>${active.map(b=>`<option value=${b.id} ${b.id===batch.id?'selected':''}>${html(b.name)} · słowa: ${b.words.length}</option>`).join('')}</select></label><div class=batch-actions><button class=quiet-button id=batch-bulk-images ${batch.stage==='published'?'disabled':''}>Wgraj grafiki grupą</button><button class=quiet-button id=batch-export>Eksportuj listę</button></div></div><div class=batch-steps aria-label="Etapy akceptacji"><span class="${batch.stage==='proposed'?'current':'done'}">1 · Lista</span><span class="${batch.stage==='images'?'current':batch.stage==='published'?'done':''}">2 · Ilustracje i poziomy</span><span class="${batch.stage==='published'?'done':''}">3 · Akceptacja batcha</span></div><div class=searchbar><input id=batch-search type=search aria-label="Szukaj w batchu" placeholder="Znajdź słowo…" value="${html(this.search)}"><select id=batch-filter aria-label="Filtr propozycji">${[['all','Cały batch'],['selected','Zaznaczone'],['missing','Do uzupełnienia'],['ready','Gotowe do akceptacji']].map(([v,n])=>`<option value=${v} ${v===this.filter?'selected':''}>${n}</option>`).join('')}</select></div><div class=batch-selection><label><input id=batch-select-all type=checkbox ${batch.words.every(r=>r.selected)?'checked':''} ${batch.stage==='published'?'disabled':''}>Zaznacz cały batch</label><span id=batch-counts></span></div><div id=batch-rows></div><div class=batch-bottom id=batch-bottom></div>`:'<section class=panel><h3>Kolejka jest pusta</h3><p>Dodaj listę słów. Kategorie sprawdzimy przed umieszczeniem ich w batchu.</p></section>'}</div>`;
  this.renderRows();
 }
 renderRows(){
  const batch=this.batch,node=this.workspace.querySelector('#batch-rows');if(!node||!batch)return;
  const {assets,words}=this.data,selected=batch.words.filter(r=>r.selected),ready=selected.filter(r=>!candidateProblems(r,assets,batch.stage==='published'?[]:words).length);
  const rows=batch.words.filter(r=>(!this.search||r.word.includes(this.search.toLocaleLowerCase('pl')))&&(this.filter!=='selected'||r.selected)&&(this.filter!=='missing'||r.selected&&candidateProblems(r,assets,batch.stage==='published'?[]:words).length)&&(this.filter!=='ready'||r.selected&&!candidateProblems(r,assets,batch.stage==='published'?[]:words).length));
  const all=this.workspace.querySelector('#batch-select-all');if(all)all.indeterminate=selected.length>0&&selected.length<batch.words.length;
  this.workspace.querySelector('#batch-counts').textContent=`${selected.length}/${batch.words.length} wybranych · ${ready.length} gotowych · ${selected.length-ready.length} do uzupełnienia`;
  node.innerHTML=rows.map(r=>{
   const issues=candidateProblems(r,assets,batch.stage==='published'?[]:words),uses=r.assetPath?new Set([...Object.entries(assets.words).filter(([,a])=>a.path===r.assetPath).map(([w])=>w),...batchWords(this.data.batches).filter(w=>w.assetPath===r.assetPath).map(w=>w.word)]).size:0;
   const detected=[...new Set(wordSlots({word:r.word}).map(s=>s.category))];
   return `<article class="batch-word ${r.selected?'':'excluded'} ${issues.length?'':'ready'}"><label class=batch-word-name><input type=checkbox data-candidate-select=${r.id} aria-label="Włącz hasło ${html(r.word)}" ${r.selected?'checked':''} ${batch.stage==='published'?'disabled':''}><strong>${html(r.word)}</strong></label><div class=batch-word-body><div class=batch-picture>${r.assetPath?`<img src="${html(this.image(r.assetPath))}" alt="${html(r.word)}" loading=lazy>`:'<span aria-label="Brak ilustracji">＋</span>'}<small>${uses>1?`Wspólna ilustracja: ${uses} słów`:r.assetPath?'Jedna ilustracja':'Dodaj ilustrację'}</small></div><div class=batch-word-details><div class=batch-category-levels>${detected.map(c=>{const enabled=r.categories.includes(c),slot=wordSlots({word:r.word}).find(s=>s.category===c);return `<label class="${enabled?'':'category-disabled'}"><span><input type=checkbox data-candidate-category=${r.id} data-category="${c}" aria-label="Ćwicz ${html(r.word)} w kategorii ${c}" ${enabled?'checked':''} ${batch.stage==='published'?'disabled':''}> ${c} <code>${html(slot.masked)}</code></span><select data-candidate-level=${r.id} data-category="${c}" aria-label="Poziom: ${html(r.word)} · ${c}" ${!enabled||batch.stage==='published'?'disabled':''}><option value=1 ${(r.levels[c]??1)===1?'selected':''}>Podstawowe</option><option value=2 ${r.levels[c]===2?'selected':''}>Trudne</option></select></label>`;}).join('')}</div><small class="${issues.length?'batch-warning':'batch-ok'}">${issues.length?html(issues.join(' ')):'✓ Hasło, ilustracja, kategorie i poziomy gotowe'}</small><div class=batch-actions><button class=small-button data-batch-upload=${r.id} ${batch.stage==='published'?'disabled':''}>Wgraj zdjęcie</button><button class=small-button data-batch-picture=${r.id} ${batch.stage==='published'?'disabled':''}>Wybierz z bazy</button></div></div></div></article>`;
  }).join('')||'<p class=description>Brak słów pasujących do filtra.</p>';
  this.workspace.querySelector('#batch-bottom').innerHTML=batch.stage==='published'?`<strong>✓ Batch zaakceptowany</strong><span>Hasła dodane do wspólnego szkicu. „Zapisz na GitHub” publikuje je w grze.</span>${batch.words.some(r=>!r.selected)?'<button class=quiet-button id=batch-retry>Odłożone słowa → nowy batch</button>':''}`:batch.stage==='proposed'?`<p>Zaznaczenie dotyczy całej grupy. Odznacz hasła, które Ci nie pasują. Poziomy można skorygować przed końcową akceptacją.</p><button class=solid-button id=batch-approve-list ${selected.length?'':'disabled'}>Zatwierdź listę · ${selected.length}</button>`:`<div><strong>${ready.length}/${selected.length} gotowych</strong><p>${selected.length-ready.length?'Uzupełnij grafiki lub odznacz niegotowe hasła.':'Sprawdź miniatury i poziomy, a potem zaakceptuj całą grupę.'}</p></div><button class=quiet-button id=batch-back-list>Wróć do listy</button><button class=solid-button id=batch-final-review ${selected.length&&selected.length===ready.length?'':'disabled'}>Sprawdź i zaakceptuj batch · ${selected.length}</button>`;
 }
 change(e){
  const n=e.target;if(!n.closest('[data-batch-review]'))return;
  if(n.id==='batch-select'){this.id=n.value;this.search='';this.render();return;}
  if(n.id==='batch-filter'){this.filter=n.value;this.renderRows();return;}
  if(n.id==='batch-select-all')this.mutate(b=>b.words.forEach(r=>r.selected=n.checked));
  if(n.dataset.candidateSelect)this.mutate(b=>b.words.find(r=>r.id===n.dataset.candidateSelect).selected=n.checked);
  if(n.dataset.candidateCategory){
   const row=this.batch.words.find(r=>r.id===n.dataset.candidateCategory);
   if(!n.checked&&row.categories.length===1){n.checked=true;this.notice('Hasło musi mieć co najmniej jedną kategorię. Jeśli nie nadaje się do żadnej, odznacz całe słowo.');return;}
   this.mutate(b=>{const item=b.words.find(r=>r.id===n.dataset.candidateCategory),detected=[...new Set(wordSlots({word:item.word}).map(s=>s.category))];if(n.checked)item.levels[n.dataset.category]??=1;else delete item.levels[n.dataset.category];item.categories=detected.filter(c=>c===n.dataset.category?n.checked:item.categories.includes(c));});
  }
  if(n.dataset.candidateLevel)this.mutate(b=>b.words.find(r=>r.id===n.dataset.candidateLevel).levels[n.dataset.category]=Number(n.value));
 }
 mutate(fn){if(this.batch.stage==='published')return;const focused=document.activeElement,selector=focused?.dataset.candidateSelect?`[data-candidate-select="${focused.dataset.candidateSelect}"]`:focused?.dataset.candidateCategory?`[data-candidate-category="${focused.dataset.candidateCategory}"][data-category="${focused.dataset.category}"]`:focused?.dataset.candidateLevel?`[data-candidate-level="${focused.dataset.candidateLevel}"][data-category="${focused.dataset.category}"]`:focused?.id?'#'+focused.id:null;this.changeBatches(next=>fn(next.batches.find(b=>b.id===this.id)));this.render();if(selector)this.workspace.querySelector(selector)?.focus({preventScroll:true});}
 async click(e){
  const n=e.target.closest('button');if(!n||!n.closest('[data-batch-review]'))return;
  if(n.dataset.historyBatch){const batch=this.data.batches.batches.find(b=>b.id===n.dataset.historyBatch);if(batch)this.history(batch);}
  if(n.id==='batch-retry'){try{const next=requeueRejected(this.data.batches,this.batch.id);this.replaceBatches(next);this.id=next.batches.at(-1).id;this.render();this.notice('Odłożone hasła wróciły do oceny w nowej grupie.');}catch(e){this.notice(e.message);}}
  if(n.id==='new-word-batch')this.newBatch();
  if(n.id==='batch-approve-list')this.mutate(b=>b.stage='images');
  if(n.id==='batch-back-list')this.mutate(b=>b.stage='proposed');
  if(n.id==='batch-final-review')this.review();
  if(n.dataset.batchUpload)this.upload(this.batch.words.find(r=>r.id===n.dataset.batchUpload).word);
  if(n.dataset.batchPicture)this.pick(this.batch.words.find(r=>r.id===n.dataset.batchPicture));
  if(n.id==='batch-bulk-images')this.bulk();
  if(n.id==='batch-export')this.download(this.batch.words.filter(r=>r.selected).map(r=>r.word).join('\n'),this.batch.id+'.txt');
 }
 newBatch(){
  this.dialog(`<h2>Dodaj batch słów</h2><p>Jedno hasło w wierszu. Wykryjemy kategorie i odrzucimy powtórzenia przed dodaniem do listy.</p><form id=batch-new-form><label class=form-field><span>Nazwa grupy</span><input name=name value="Nowa grupa" maxlength=100 required></label><label class=form-field><span>Lista słów</span><textarea name=words rows=9 required placeholder="Jedno słowo w każdym wierszu"></textarea></label><p id=batch-import-error role=alert></p><div class=modal-actions><button type=button class=quiet-button data-close>Anuluj</button><button class=solid-button>Sprawdź i dodaj listę</button></div></form>`);
  this.modal.querySelector('form').onsubmit=e=>{e.preventDefault();try{const form=new FormData(e.target),result=addCandidates(this.data.batches,String(form.get('words')).split(/[\n,;]+/).map(s=>s.trim()).filter(Boolean),this.data.words,{name:String(form.get('name')).trim()});if(!result.added)throw Error(result.rejected.map(r=>r.word+': '+r.reason).join(' '));this.replaceBatches(result.value);this.id=result.value.batches.at(-1).id;this.modal.close();this.render();this.notice(`Dodano ${result.added}. Pominięto ${result.rejected.length} powtórzeń lub niepasujących haseł.`);}catch(error){this.modal.querySelector('#batch-import-error').textContent=error.message;}};
 }
 pick(row){
  const {assets,words}=this.data,namesFor=path=>[...new Set([...Object.entries(assets.words).filter(([,r])=>(assets.aliases[r.path]||r.path)===path).map(([w])=>w),...batchWords(this.data.batches).filter(r=>(assets.aliases[r.assetPath]||r.assetPath)===path).map(r=>r.word)])],choices=assets.assets.filter(a=>['scenes','managed'].includes(a.group)&&!assets.aliases[a.path]);
  this.dialog(`<h2>Ilustracja: ${html(row.word)}</h2><p>Wybierz jeden plik dla wszystkich kategorii tego słowa. Możesz ponownie użyć ilustracji powiązanej z innymi hasłami.</p><input id=batch-picture-search type=search aria-label="Szukaj ilustracji" placeholder="Szukaj po słowie…"><div class="batch-picture-picker" id=batch-picture-grid></div><p id=batch-picture-error role=alert></p><div class=modal-actions><button class=quiet-button data-close>Zamknij</button></div>`);
  const render=()=>{const q=this.modal.querySelector('#batch-picture-search').value.toLocaleLowerCase('pl');this.modal.querySelector('#batch-picture-grid').innerHTML=choices.filter(a=>!q||namesFor(a.path).some(w=>w.includes(q))||a.path.includes(q)).slice(0,60).map(a=>{const names=namesFor(a.path);return `<button class=batch-picture-choice data-pick-batch-path="${html(a.path)}"><img src="${html(this.image(a.path))}" alt="${html(names.join(', ')||'Wgrana ilustracja')}" loading=lazy><span>${html(names.slice(0,3).join(', ')||'Wgrana ilustracja')}</span><small>Powiązane hasła: ${names.length}</small></button>`;}).join('');};render();this.modal.querySelector('#batch-picture-search').oninput=render;
  this.modal.querySelector('#batch-picture-grid').onclick=async e=>{const button=e.target.closest('[data-pick-batch-path]');if(!button)return;try{const path=button.dataset.pickBatchPath,image=new Image();image.src=this.image(path);await image.decode();if(Math.abs(image.naturalWidth/image.naturalHeight-1)>.04)throw Error('Ilustracja słowa powinna być kwadratowa.');await this.choosePicture(row.id,path,{width:image.naturalWidth,height:image.naturalHeight});this.modal.close();this.render();}catch(error){this.modal.querySelector('#batch-picture-error').textContent=error.message;}};
 }
 bulk(){
  this.dialog(`<h2>Grafiki dla całego batcha</h2><p>Nazwij pliki jak hasła, np. „śnieg.jpg” lub „snieg.jpg”. Dopasowanie musi być jednoznaczne. Do 48 plików i 64 MB w jednej grupie.</p><input id=batch-image-files type=file accept="image/png,image/jpeg,image/webp,image/avif" multiple><p id=batch-image-status role=status></p><div class=modal-actions><button class=quiet-button data-close>Zamknij</button></div>`);
  this.modal.querySelector('#batch-image-files').onchange=async e=>{const status=this.modal.querySelector('#batch-image-status');try{status.textContent='Sprawdzamy pliki…';const result=await this.addImages([...e.target.files],this.batch.id);status.textContent=`Dodano ${result.added} ilustracji. ${result.errors.join(' ')}`;this.render();}catch(error){status.textContent=error.message;}};
 }
 history(batch){
  const rows=batch.words.filter(r=>r.selected);
  this.dialog(`<h2>${html(batch.name)}</h2><p><strong>✓ Batch zakończony</strong> · ${rows.length} zaakceptowanych słów.</p><div class=batch-review-grid>${rows.map(r=>`<article>${r.assetPath?`<img src="${html(this.image(r.assetPath))}" alt="${html(r.word)}">`:''}<strong>${html(r.word)}</strong><small>${r.categories.map(c=>`${c}: ${r.levels[c]===1?'podstawowe':'trudne'}`).join(' · ')}</small></article>`).join('')}</div><div class=modal-actions><button class=quiet-button data-close>Zamknij</button></div>`);
 }
 review(){
  const batch=this.batch,rows=batch.words.filter(r=>r.selected);
  this.dialog(`<h2>Końcowa akceptacja batcha</h2><p><strong>${html(batch.name)}</strong> · ${rows.length} słów. Sprawdź całą grupę: hasło, zdjęcie, kategorie oraz poziomy.</p><div class=batch-review-grid>${rows.map(r=>`<article><img src="${html(this.image(r.assetPath))}" alt="${html(r.word)}"><strong>${html(r.word)}</strong><small>${r.categories.map(c=>`${c}: ${r.levels[c]===1?'podstawowe':'trudne'}`).join(' · ')}</small></article>`).join('')}</div><p id=batch-publish-error role=alert></p><div class=modal-actions><button class=quiet-button data-close>Jeszcze sprawdzę</button><button class=solid-button id=batch-publish-confirm>Akceptuj cały batch · ${rows.length}</button></div>`);
  this.modal.querySelector('#batch-publish-confirm').onclick=async e=>{e.target.disabled=true;try{await this.publish(batch.id);this.id=this.data.batches.batches.find(b=>b.stage!=='published')?.id||'';this.search='';this.filter='all';this.modal.close();this.render();this.notice('Batch zaakceptowany. Przełączono na następną aktywną grupę. Zapisz na GitHub, aby hasła trafiły do gry.');}catch(error){this.modal.querySelector('#batch-publish-error').textContent=error.message;e.target.disabled=false;}};
 }
}
