import {DEFAULT_LOGO_TRANSITION,LOGO_FIELDS,logoConfig,logoTiming} from '../shared/logo-transition.mjs';
import {html} from './preview-model.mjs';
import {jellyChoices,mountJellies} from './studio-jelly.mjs';
const GROUPS=[['Obroty i kształty',['turns','turnDuration','orbitRadius','shapeSize','morph']],['Kolorowe bloby',['splashDuration','overlap','randomness','seed']],['Biały blob i wejście',['whiteDuration','whiteWobble','revealAt','revealDuration']]];
export class StudioLogo{
 constructor(options){Object.assign(this,options);this.view='home';this.time=0;this.ready=false;this.playing=false;this.loop=false;this.panel=true;this.workspace.addEventListener('click',e=>this.click(e));this.workspace.addEventListener('input',e=>this.input(e));this.workspace.addEventListener('change',e=>this.change(e));window.addEventListener('message',e=>this.receive(e));}
 get isOpen(){return Boolean(this.workspace.querySelector('.logo-lab'));}
 get config(){return logoConfig(this.getDesign().config.logoTransition);}
 frame(){return this.workspace.querySelector('#logo-frame');}
 post(type,extra={}){this.frame()?.contentWindow?.postMessage({channel:'mala-nauka-logo',type,config:this.config,...extra},location.origin);}
 render(){this.leave();this.ready=false;const v=this.registry.views.find(v=>v.id===this.view)||this.registry.views[0],url=new URL(v.route,location.origin);url.search=new URLSearchParams({studio:'1',mode:v.mode,screen:v.screen,state:v.state,viewId:v.id});
 this.workspace.innerHTML=this.sectionNav()+`<section class="logo-lab" data-mobile-editor=motion><div class=logo-preview><div class=logo-toolbar>${jellyChoices('logo-target','Widok',this.registry.views.filter(v=>['home','spelling-settings','english-settings','math-settings'].includes(v.id)).map(v=>[v.id,v.name]),this.view)}<div class=logo-tools><button class=small-button id=logo-play disabled>▶ Odtwórz</button><button class=small-button id=logo-pause>Ⅱ</button><button class=small-button id=logo-reset title="Wróć do początku">↶</button><label><input id=logo-loop type=checkbox ${this.loop?'checked':''}> Pętla</label><button class=small-button id=logo-panel title="Pokaż / schowaj ustawienia">⚙</button></div></div><div class=logo-stage><div class=logo-phone><iframe id=logo-frame title="Animacja i prawdziwy ekran Małej Nauki" src="${html(url.href)}" width=390 height=844></iframe></div></div><div class=logo-timeline><span id=logo-state>Ładowanie podglądu…</span><output id=logo-time>0 s</output><input type=range id=logo-seek aria-label="Klatka animacji" min=0 max=${logoTiming(this.config).total} step=20 value=0><div class=logo-phases>${[['orbit','Obrót'],['splash','Kolory'],['white','Biały blob'],['reveal','Wejście']].map(([id,name])=>`<button class=small-button data-logo-phase=${id}>${name}</button>`).join('')}</div></div></div><aside class="inspector logo-inspector" id=logo-inspector><header><span class=eyebrow>Animowane elementy</span><h2>Lab logo</h2><label><input type=checkbox id=logo-enabled ${this.config.enabled?'checked':''}> Używaj przy ładowaniu PWA</label></header>${GROUPS.map(([name,keys],i)=>`<details class=motion-control-group ${i===0?'open':''}><summary>${name}</summary><div class=motion-control-body>${keys.map(key=>this.control(key)).join('')}</div></details>`).join('')}<details class=motion-control-group><summary>Pięć kolorów logo</summary><div class="motion-control-body logo-colors">${this.config.colors.map((color,i)=>`<label>Tryb ${i+1}<input type=color data-logo-color=${i} value=${color}></label>`).join('')}</div></details><button class=small-button id=logo-defaults>Przywróć przepis</button></aside></section>`;mountJellies(this.workspace);this.workspace.querySelectorAll('.logo-inspector details').forEach(el=>el.addEventListener('toggle',()=>{if(el.open)for(const other of this.workspace.querySelectorAll('.logo-inspector details'))if(other!==el)other.open=false;}));this.resizeObserver?.disconnect();this.resizeObserver=new ResizeObserver(()=>this.fit());this.resizeObserver.observe(this.workspace.querySelector('.logo-stage'));this.fit();}
 control(key){const [min,max,step,label]=LOGO_FIELDS[key];return `<div class=control><div class=control-top><label>${label}</label><input type=number data-logo-field=${key} aria-label="${label}" value=${this.config[key]} min=${min} max=${max} step=${step}></div><input type=range data-logo-field=${key} aria-label="${label}" value=${this.config[key]} min=${min} max=${max} step=${step}></div>`;}
 fit(){const stage=this.workspace.querySelector('.logo-stage');if(!stage)return;const scale=Math.max(.15,Math.min(1,(stage.clientHeight-24)/844,(stage.clientWidth-24)/390));stage.style.setProperty('--logo-scale',scale);}
 sendDesign(){if(!this.isOpen)return;const frame=this.frame();frame?.contentWindow?.postMessage({channel:'mala-nauka-studio',type:'design',...this.getDesign()},location.origin);if(this.ready){this.playing=false;this.post('stop');this.post('seek',{time:this.time});}const seek=this.workspace.querySelector('#logo-seek');if(seek)seek.max=logoTiming(this.config).total;}
 receive(e){if(!this.isOpen||e.origin!==location.origin||e.source!==this.frame()?.contentWindow)return;if(e.data?.channel==='mala-nauka-studio'&&e.data.type==='ready'){this.ready=true;this.frame().contentWindow.postMessage({channel:'mala-nauka-studio',type:'design',...this.getDesign()},location.origin);this.frame().contentWindow.postMessage({channel:'mala-nauka-studio',type:'inspect',enabled:false,highlight:false},location.origin);this.workspace.querySelector('#logo-play').disabled=false;this.post('seek',{time:0});}if(e.data?.channel==='mala-nauka-logo'&&e.data.type==='frame'){this.time=e.data.time;this.workspace.querySelector('#logo-state').textContent=e.data.stage;this.workspace.querySelector('#logo-time').textContent=(this.time/1000).toFixed(2)+' s';this.workspace.querySelector('#logo-seek').value=this.time;}if(e.data?.channel==='mala-nauka-logo'&&e.data.type==='finished'){this.playing=false;if(this.loop){this.time=0;this.playing=true;this.post('start');}}}
 click(e){if(!this.isOpen)return;const b=e.target.closest('button');if(!b)return;if(b.id==='logo-play'){this.playing=true;if(this.time>=logoTiming(this.config).total)this.time=0;this.post('start',{time:this.time});}if(b.id==='logo-pause'){this.playing=false;this.post('pause');}if(b.id==='logo-reset'){this.time=0;this.playing=false;this.post('seek',{time:0});}if(b.id==='logo-defaults'){this.edit('logoTransition',structuredClone(DEFAULT_LOGO_TRANSITION));this.endEdit();this.render();}if(b.id==='logo-panel'){this.panel=!this.panel;this.workspace.querySelector('.logo-lab').classList.toggle('panel-hidden',!this.panel);}if(b.dataset.logoPhase){const t=logoTiming(this.config),times={orbit:1000,splash:t.orbit+this.config.splashDuration*.65,white:t.white+this.config.whiteDuration*.32,reveal:t.reveal+this.config.revealDuration*.5};this.playing=false;this.post('seek',{time:times[b.dataset.logoPhase]});}}
 input(e){if(!this.isOpen)return;const n=e.target;if(n.id==='logo-seek'){this.playing=false;this.post('seek',{time:Number(n.value)});return;}if(n.dataset.logoField){const key=n.dataset.logoField,[min,max]=LOGO_FIELDS[key],value=Math.max(min,Math.min(max,Number(n.value)));if(!Number.isFinite(value))return;this.edit('logoTransition.'+key,value);for(const field of this.workspace.querySelectorAll(`[data-logo-field=${key}]`))if(field!==n)field.value=value;}if(n.dataset.logoColor!==undefined){const colors=[...this.config.colors];colors[Number(n.dataset.logoColor)]=n.value;this.edit('logoTransition.colors',colors);}}
 change(e){if(!this.isOpen)return;const n=e.target;if(n.dataset.studioNav==='logo-target'){this.view=n.value;this.time=0;this.render();}if(n.id==='logo-loop')this.loop=n.checked;if(n.id==='logo-enabled')this.edit('logoTransition.enabled',n.checked);this.endEdit();}
 leave(){this.post('stop');this.resizeObserver?.disconnect();this.playing=false;}
}
